export const TRIP_INFO = {
    dates: "Dec 9–13, 2025",
    travellers: 2,
    car: "Kia Sportage",
    hotel: "Hotel 201, Kópavogur",
    hotelCoords: { lat: 64.0974639, lng: -21.8893358 },
    breakfast: "Included at hotel",
    currency: "EUR",
  };
  
  export const AURORA_LINKS = [
    { label: "Aurora forecast (vedur.is)", url: "https://en.vedur.is/weather/forecasts/aurora/" },
    { label: "Cloud cover map", url: "https://en.vedur.is/weather/forecasts/elements/#type=CC" },
    { label: "Grótta tide times (saeferdin.is)", url: "https://www.saeferdin.is/" },
    { label: "Space Weather Live KP", url: "https://www.spaceweatherlive.com/en/solar-activity/kp-index.html" },
  ];
  
  // Daily Google Maps route links (multi-stop directions)
  export const DAILY_ROUTES = {
    1: {
      label: "Day 1 route — Hotel → Loving Hut → Lava Tunnel area",
      url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Loving+Hut+Reykjavik/Raufarholshellir+Lava+Tunnel+Iceland",
    },
    2: {
      label: "Day 2 route — South Coast full loop",
      url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Seljalandsfoss+Iceland/Skogafoss+Iceland/Sudur-Vik+Vik+Iceland/Solheimasandur+Plane+Wreck/Solheimajokull+Glacier/Reynisfjara+Black+Sand+Beach/Hotel+201+Kopavogur",
    },
    3: {
      label: "Day 3 route — Golden Circle",
      url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Thingvellir+National+Park/Geysir+Iceland/Gullfoss+Iceland/Kerid+Crater+Iceland/Kleifarvatn+Lake+Iceland/Hotel+201+Kopavogur",
    },
    4: {
      label: "Day 4 route — Reykjavík city + Sky Lagoon + Grótta",
      url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Hallgrimskirkja+Reykjavik/101+Reykjavik+Street+Food/Sky+Lagoon+Reykjavik/Grotta+Lighthouse+Seltjarnarnes",
    },
    5: {
      label: "Day 5 — Hotel → Keflavík Airport",
      url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Keflavik+International+Airport",
    },
  };
  
  export const CAFES = [
    {
      id: "braud-co",
      name: "Brauð & Co",
      type: "Bakery",
      emoji: "🥐",
      address: "Frakkastígur 16, 101 Reykjavík",
      hours: "Mon–Sat 6:30am–5pm · Sun 6:30am–5pm",
      rating: 4.8,
      reviews: 4719,
      mustTry: "Cinnamon roll (legendary), caramel & müsti pastry",
      price: "€4–6/item",
      note: "Iceland's most famous bakery. Opens early — perfect before a day trip. Mostly takeaway.",
      mapsUrl: "https://maps.google.com/?cid=14908391867206714937",
      bestDay: "Day 4 morning (steps from Hallgrímskirkja)",
    },
    {
      id: "sandholt",
      name: "Sandholt",
      type: "Bakery & Café",
      emoji: "☕",
      address: "Laugavegur 36, 101 Reykjavík",
      hours: "Daily 7:30am–6pm",
      rating: 4.6,
      reviews: 4285,
      mustTry: "Cream puffs, Danish pastries, sourdough, oat latte",
      price: "€5–8/item",
      note: "Family-run since 1920s. Sit-down available. Can get busy — go early or late.",
      mapsUrl: "https://maps.google.com/?q=Sandholt+Reykjavik",
      bestDay: "Day 4 — on Laugavegur shopping walk",
    },
    {
      id: "lookoomas",
      name: "Loo.koo.mas",
      type: "Dessert & Donuts",
      emoji: "🍩",
      address: "Laugavegur 30a, 101 Reykjavík",
      hours: "Daily 2:30pm–11pm",
      rating: 4.9,
      reviews: 1560,
      mustTry: "Greek loukoumades (honey donuts), Caramel Sin, hot chocolate",
      price: "€6–9/portion",
      note: "Highest rated sweet shop in Reykjavík. Evening only. Perfect after Sky Lagoon on Day 4.",
      mapsUrl: "https://maps.google.com/?q=Lookumas+Reykjavik",
      bestDay: "Day 4 evening — after Sky Lagoon dinner",
    },
    {
      id: "sweet-aurora",
      name: "Sweet Aurora",
      type: "French Patisserie",
      emoji: "🍰",
      address: "Bergstaðastræti 14, 101 Reykjavík",
      hours: "Tue–Sat 10am–6pm · Sun 10am–5pm · Closed Mon",
      rating: 4.9,
      reviews: 270,
      mustTry: "Lava flow chocolate cake, Mont Blanc, tarte au citron, maple spiced latte",
      price: "€6–10/item",
      note: "Tiny French patisserie by Paul Bocuse-trained chef. Seasonal Iceland-inspired creations. Hidden gem.",
      mapsUrl: "https://maps.google.com/?q=Sweet+Aurora+Reykjavik",
      bestDay: "Day 4 — near Laugavegur",
    },
  ];
  
  export const DAYS = [
    {
      id: 1,
      date: "Tue Dec 9",
      title: "Arrival + Lava Tunnel & Northern Lights",
      badge: "Light day • Tour night",
      badgeColor: "purple",
      kmDriving: 60,
      parkingCostEur: 0,
      routeKey: 1,
      stops: [
        {
          id: "d1-arrive",
          time: "~14:30",
          icon: "✈️",
          name: "Arrive KEF · Collect Kia Sportage",
          note: "4AM start from Berlin — take it easy. Drive ~45 min to Hotel 201. Register rental plate in Parka + EasyPark apps immediately at car counter.",
          tags: ["Hotel 201 — free parking"],
          parking: { fee: "Free", app: "n/a", notes: "Hotel on-site lot" },
          cost: null,
          mapsUrl: "https://maps.google.com/?q=Keflavik+International+Airport",
          category: "transport",
        },
        {
          id: "d1-dinner",
          time: "16:30",
          icon: "🍜",
          name: "Early dinner — Loving Hut",
          note: "Fully vegan. Asian soups, noodles, generous portions. Eat well before the long evening tour. Budget ~€12–15/person. Open until 9pm.",
          tags: ["100% vegan", "€12–15/person", "4.7★"],
          cost: { label: "Dinner x2", eur: 30 },
          mapsUrl: "https://maps.google.com/?q=Loving+Hut+Reykjavik+Laugavegur",
          category: "food",
        },
        {
          id: "d1-rest",
          time: "18:30",
          icon: "🛋️",
          name: "Rest at hotel · Layer up · Head out by 19:15",
          note: "Charge cameras, power banks, phones. Thermal base layer + fleece + windproof outer. Be at pickup 15 min early.",
          tags: ["Pickup: central Reykjavík"],
          cost: null,
          mapsUrl: null,
          category: "rest",
        },
        {
          id: "d1-tour",
          time: "19:30",
          icon: "🌌",
          name: "Lava Tunnel & Northern Lights Tour (booked)",
          note: "Bus picks up at 19:30 from central Reykjavík. Visit Raufarhólshellir lava cave + aurora chasing in dark countryside. ~4–5h. Helmets, headlamps & hot drinks included. Free re-try if no aurora!",
          tags: ["adventures.is", "Pre-booked", "~$207/person", "Free re-try"],
          cost: { label: "Tour pre-paid", eur: null },
          mapsUrl: "https://maps.google.com/?q=Raufarholshellir+Lava+Tunnel+Iceland",
          category: "aurora",
        },
      ],
      auroraSpot: {
        name: "Tour guides chase aurora for you tonight",
        note: "Relax — the guide monitors the forecast and drives to the best spot. Nothing to plan.",
        free: true,
      },
    },
    {
      id: 2,
      date: "Wed Dec 10",
      title: "South Coast",
      badge: "Full day • Aurora evening",
      badgeColor: "blue",
      kmDriving: 390,
      parkingCostEur: 25,
      routeKey: 2,
      stops: [
        {
          id: "d2-breakfast",
          time: "08:30",
          icon: "☕",
          name: "Breakfast at Hotel 201 (included) · Depart 09:30",
          note: "Pack thermos + snacks. Stock up at Bónus supermarket the night before. Biggest driving day of the trip.",
          tags: ["Breakfast included"],
          cost: null,
          mapsUrl: null,
          category: "food",
        },
        {
          id: "d2-seljalandsfoss",
          time: "~11:10",
          icon: "💧",
          name: "Seljalandsfoss Waterfall",
          note: "Walk behind the waterfall curtain — magical but icy in December. Waterproof shoes essential. Path can close if too slippery. Also visit nearby Gljúfrabúi hidden waterfall (5 min walk). Allow 45 min.",
          tags: ["Free entry", "4.8★ · 3,418 reviews"],
          parking: { fee: "€7 (1,000 ISK)", app: "Checkit.is or card kiosk", notes: "Flat fee, all day" },
          cost: { label: "Parking", eur: 7 },
          mapsUrl: "https://maps.google.com/?cid=12538555864065841037",
          category: "nature",
          warning: "Icy path — possible closure in Dec",
        },
        {
          id: "d2-skogafoss",
          time: "~12:10",
          icon: "💧",
          name: "Skógafoss Waterfall",
          note: "20 min east. Iceland's most photogenic waterfall. Climb the staircase on the right for elevated views. Winter spray can freeze into stunning ice formations. Allow 45 min.",
          tags: ["Free entry", "4.9★ · 4,379 reviews"],
          parking: { fee: "€7 (1,000 ISK)", app: "Parka loc 8205", notes: "8h valid" },
          cost: { label: "Parking", eur: 7 },
          mapsUrl: "https://maps.google.com/?cid=1108104447747062088",
          category: "nature",
        },
        {
          id: "d2-lunch",
          time: "~13:15",
          icon: "🍲",
          name: "Lunch — Suður-Vík Restaurant, Vík",
          note: "30 min drive to Vík village. Best restaurant on the South Coast. Open from noon. Ask for vegetable soup + bread — very warming. ~€8–10. 4.7★ with 2,856 reviews.",
          tags: ["Veggie soup ✓", "Open noon–9pm", "4.7★"],
          cost: { label: "Lunch x2", eur: 20 },
          mapsUrl: "https://maps.google.com/?cid=7641495306756877372",
          category: "food",
        },
        {
          id: "d2-dc3",
          time: "~14:15",
          icon: "✈️",
          name: "DC-3 Plane Wreck · Sólheimasandur",
          note: "10 min from Vík. Paid parking then shuttle bus or 4 km walk. Haunting rusted wreck on vast black plains. Very exposed and windy — full windproof essential. Allow 1.5–2h with shuttle.",
          tags: ["3.9★ · Shuttle recommended", "Windproof essential"],
          parking: { fee: "€5 (750 ISK)", app: "Parka", notes: "Shuttle extra: €14/way (2,000 ISK)" },
          cost: { label: "Parking + shuttle x2", eur: 33 },
          mapsUrl: "https://maps.google.com/?cid=17133397352151561316",
          category: "nature",
          warning: "Very cold and exposed — dress in full layers",
        },
        {
          id: "d2-glacier",
          time: "~16:00",
          icon: "🏔️",
          name: "Sólheimajökull Glacier",
          note: "15 min from wreck. Short 10-min flat walk to glacier tongue. Black volcanic ash on white ice — surreal scenery. Allow 30–35 min. Light fades fast.",
          tags: ["Free entry", "4.9★ · 357 reviews"],
          parking: { fee: "€7 (1,000 ISK)", app: "Parka", notes: "" },
          cost: { label: "Parking", eur: 7 },
          mapsUrl: "https://maps.google.com/?cid=6569487264573684022",
          category: "nature",
        },
        {
          id: "d2-reynisfjara",
          time: "~16:45",
          icon: "🏖️",
          name: "Reynisfjara Black Sand Beach",
          note: "20 min drive. Basalt columns + Reynisdrangar sea stacks. Dark by arrival — bring torch. Extraordinary at night. Stay for aurora if sky clears.",
          tags: ["Free entry", "4.8★ · 2,440 reviews"],
          parking: { fee: "€7 lower / €5 upper (1,000/750 ISK)", app: "Parka loc 8202", notes: "3h limit" },
          cost: { label: "Parking", eur: 7 },
          mapsUrl: "https://maps.google.com/?cid=4116293821646712216",
          category: "nature",
          warning: "⚠️ Rogue waves fatal — stay 30m+ from waterline",
        },
      ],
      auroraSpot: {
        name: "Reynisfjara Beach or Vík outskirts",
        note: "Already there at nightfall. Zero light pollution. Stay if KP ≥ 3 + clear sky. Drive back by 20:30 (2h 30min to hotel).",
        free: true,
      },
    },
    {
      id: 3,
      date: "Thu Dec 11",
      title: "Golden Circle",
      badge: "Full day • Aurora evening",
      badgeColor: "blue",
      kmDriving: 260,
      parkingCostEur: 22,
      routeKey: 3,
      stops: [
        {
          id: "d3-breakfast",
          time: "08:30",
          icon: "☕",
          name: "Breakfast at Hotel 201 (included) · Depart 09:30",
          tags: ["Breakfast included"],
          cost: null,
          mapsUrl: null,
          category: "food",
        },
        {
          id: "d3-thingvellir",
          time: "~10:15",
          icon: "🌋",
          name: "Þingvellir National Park",
          note: "45 min drive. Walk the Almannagjá gorge between the North American and Eurasian tectonic plates. Iceland's first parliament site 930 AD. UNESCO World Heritage. Allow 1–1.5h.",
          tags: ["Free entry", "UNESCO", "4.7★ · 24,206 reviews"],
          parking: { fee: "€7 (1,000 ISK)", app: "Checkit.is", notes: "Valid all lots, all day" },
          cost: { label: "Parking", eur: 7 },
          mapsUrl: "https://maps.google.com/?cid=7743214478716723954",
          category: "nature",
        },
        {
          id: "d3-geysir",
          time: "~12:00",
          icon: "♨️",
          name: "Geysir Geothermal Area",
          note: "45 min from Þingvellir. Strokkur erupts every 5–10 min — camera ready! Geysir Bistro has hot vegetable soup. Allow 1h.",
          tags: ["Free entry", "4.7★ · 4,702 reviews", "Soup at Geysir Bistro"],
          parking: { fee: "€7 (1,000 ISK)", app: "Parka", notes: "" },
          cost: { label: "Parking + soup x2", eur: 21 },
          mapsUrl: "https://maps.google.com/?cid=15747725443058989029",
          category: "nature",
        },
        {
          id: "d3-gullfoss",
          time: "~13:30",
          icon: "💧",
          name: "Gullfoss Waterfall",
          note: "10 min from Geysir. Two-tier cascade into a canyon. December spray freezes into stunning ice sculptures. Gullfoss café on site. Allow 45 min.",
          tags: ["Free entry", "FREE parking", "4.9★ · 5,559 reviews"],
          parking: { fee: "Free", app: "n/a", notes: "Free car park on-site" },
          cost: null,
          mapsUrl: "https://maps.google.com/?cid=3198479166475408897",
          category: "nature",
        },
        {
          id: "d3-kerid",
          time: "~15:00",
          icon: "⭕",
          name: "Kerið Volcanic Crater",
          note: "~55 min south. Vivid red and green volcanic crater with a lake inside. Walk the rim at last light, or descend steps to the floor. Admission at gate kiosk (card accepted). Allow 30–40 min.",
          tags: ["Entry: €4/person at kiosk", "4.5★ · 19,973 reviews"],
          parking: { fee: "Free", app: "n/a", notes: "Free parking; entry separate" },
          cost: { label: "Entry x2", eur: 8 },
          mapsUrl: "https://maps.google.com/?cid=5862073597080557831",
          category: "nature",
        },
        {
          id: "d3-dinner",
          time: "17:30",
          icon: "🍜",
          name: "Dinner — Loving Hut or Chickpea",
          note: "Back in Reykjavík. Loving Hut for Asian soups/noodles or Chickpea for falafel wraps (Chickpea closed Sundays). Both ~€10–15/person.",
          tags: ["Vegetarian ✓", "Budget-friendly"],
          cost: { label: "Dinner x2", eur: 28 },
          mapsUrl: "https://maps.google.com/?q=Loving+Hut+Reykjavik",
          category: "food",
        },
      ],
      auroraSpot: {
        name: "Kleifarvatn Lake (40 min) or Heiðmörk Reserve (20 min)",
        note: "Head out ~19:30. Kleifarvatn: volcanic lake, hills block city glow, water reflects aurora. Heiðmörk: dark lava park, closer. Both free parking. Check vedur.is first.",
        free: true,
      },
    },
    {
      id: 4,
      date: "Fri Dec 12",
      title: "Reykjavík · Hallgrímskirkja · Sky Lagoon",
      badge: "Easy day • Sky Lagoon 🌊",
      badgeColor: "pink",
      kmDriving: 35,
      parkingCostEur: 5,
      routeKey: 4,
      stops: [
        {
          id: "d4-breakfast",
          time: "09:00",
          icon: "☕",
          name: "Breakfast at Hotel 201 (included) · Relaxed start",
          note: "Last full day. No rush. Park car at hotel and taxi/drive to city centre.",
          tags: ["Breakfast included"],
          cost: null,
          mapsUrl: null,
          category: "food",
        },
        {
          id: "d4-church",
          time: "10:00",
          icon: "⛪",
          name: "Hallgrímskirkja Church + Tower",
          note: "Opens 9am daily. Take the elevator to the tower observation deck — 360° panoramic views over Reykjavík's rooftops, the harbour and mountains. Church interior free. Tower entry paid on-site. Allow 45–60 min.",
          tags: ["Church: free", "Tower: €10/person", "4.6★ · 28,272 reviews", "Opens 9am"],
          parking: { fee: "Street parking", app: "Parka or EasyPark", notes: "~€5/hr" },
          cost: { label: "Tower x2 + parking", eur: 25 },
          mapsUrl: "https://maps.google.com/?cid=17847528671789558511",
          category: "sightseeing",
        },
        {
          id: "d4-rainbow",
          time: "11:00",
          icon: "🌈",
          name: "Skólavörðustígur (Rainbow Street) + Laugavegur shopping",
          note: "Walk down the rainbow-painted street from the church to Laugavegur. Browse local wool, lava jewellery, bookshops. Allow 1–1.5h.",
          tags: ["Walking — no parking needed"],
          cost: null,
          mapsUrl: "https://maps.google.com/?q=Skolavordustigur+Reykjavik",
          category: "sightseeing",
        },
        {
          id: "d4-braud",
          time: "11:30",
          icon: "🥐",
          name: "Brauð & Co — legendary cinnamon bun",
          note: "Steps from the church on Frakkastígur. Opens 6:30am. Iceland's most famous cinnamon roll. Also try caramel & müsti pastry. Mostly takeaway — eat on the rainbow street.",
          tags: ["4.8★ · 4,719 reviews", "€4–6/item"],
          cost: { label: "Pastries x2", eur: 12 },
          mapsUrl: "https://maps.google.com/?cid=14908391867206714937",
          category: "cafe",
        },
        {
          id: "d4-lunch",
          time: "12:30",
          icon: "🧆",
          name: "Lunch — Chickpea (4.9★) or 101 Street Food",
          note: "Chickpea: outstanding falafel wraps, hummus, kimchi. 4.9★ / 449 reviews. ~€10–13. Or 101 Street Food: veggie soup + unlimited bread, ~€8–10. Both on Laugavegur. Chickpea closed Sundays.",
          tags: ["Vegetarian ✓", "€8–13/person"],
          cost: { label: "Lunch x2", eur: 24 },
          mapsUrl: "https://maps.google.com/?cid=3685237574449407097",
          category: "food",
        },
        {
          id: "d4-sandholt",
          time: "13:15",
          icon: "☕",
          name: "Sandholt Bakery — coffee & pastry break",
          note: "On Laugavegur 36. Family bakery since 1920s. Cream puffs, Danish pastries, excellent oat latte. Sit-down seating available. Go early to avoid queues.",
          tags: ["4.6★ · 4,285 reviews", "€5–8/item", "Open 7:30am–6pm"],
          cost: { label: "Coffee + pastry x2", eur: 20 },
          mapsUrl: "https://maps.google.com/?q=Sandholt+Reykjavik",
          category: "cafe",
        },
        {
          id: "d4-skylagoon",
          time: "14:00",
          icon: "🌊",
          name: "Sky Lagoon — sunset & blue hour",
          note: "5 min from Hotel 201. Arrive 14:00 to catch sunset (~15:30) from the infinity edge over the Atlantic. Saman package includes 7-step ritual: lagoon → cold pool → sauna → cold mist → sky bath → steam → salt scrub + shower. Open until 11pm. Pre-book online.",
          tags: ["Pre-book: skylagoon.com", "Saman ~€67/person", "4.7★ · 9,018 reviews", "Opens 8am · Closes 11pm"],
          parking: { fee: "Free", app: "n/a", notes: "On-site lot, no time limit" },
          cost: { label: "Saman x2", eur: 134 },
          mapsUrl: "https://maps.google.com/?cid=3079010116632733968",
          category: "spa",
        },
        {
          id: "d4-dinner",
          time: "17:30",
          icon: "🍜",
          name: "Farewell dinner — Loving Hut",
          note: "Asian soups + noodles. Big portions. ~€12–15/person. Open until 9pm (Sunday from 4pm).",
          tags: ["Vegan ✓", "Budget-friendly"],
          cost: { label: "Dinner x2", eur: 30 },
          mapsUrl: "https://maps.google.com/?q=Loving+Hut+Reykjavik+Laugavegur",
          category: "food",
        },
        {
          id: "d4-lookumas",
          time: "19:00",
          icon: "🍩",
          name: "Loo.koo.mas — Greek donuts & hot chocolate",
          note: "On the way to Grótta. 4.9★ — highest rated sweet spot in Reykjavík. Greek loukoumades (honey donuts) + hot chocolate. Perfect fuel before the aurora hunt. Open until 11pm.",
          tags: ["4.9★ · 1,560 reviews", "€6–9/portion", "Open 2:30pm–11pm"],
          cost: { label: "Dessert x2", eur: 16 },
          mapsUrl: "https://maps.google.com/?q=Lookumas+Reykjavik",
          category: "cafe",
        },
      ],
      auroraSpot: {
        name: "Grótta Lighthouse — 15 min from hotel",
        note: "Reviewers call it 'best place for Northern Lights in Reykjavík'. Check tide at saeferdin.is before walking out — path floods at high tide. Geothermal foot bath on-site. Free roadside parking.",
        free: true,
      },
    },
    {
      id: 5,
      date: "Sat Dec 13",
      title: "Departure",
      badge: "Morning only ✈️",
      badgeColor: "amber",
      kmDriving: 50,
      parkingCostEur: 0,
      routeKey: 5,
      stops: [
        {
          id: "d5-breakfast",
          time: "06:30",
          icon: "☕",
          name: "Early breakfast + checkout",
          note: "Ask hotel the night before what time breakfast opens for early departures. Pack bags the night before. Leave hotel by 07:15 latest for a 10:00–12:00 flight.",
          tags: ["Breakfast included", "⚠️ Leave by 07:15"],
          cost: null,
          mapsUrl: null,
          category: "food",
          warning: "Leave hotel no later than 07:15",
        },
        {
          id: "d5-kef",
          time: "07:15",
          icon: "🚗",
          name: "Drive to KEF + fill fuel tank + car return",
          note: "~45 min drive. Fill tank before airport — last petrol station is Olis in Keflavík town (before the airport turn). Allow 30 min for car return + shuttle to terminal.",
          tags: ["⚠️ Fill tank at Olis, Keflavík", "Car return: allow 30 min"],
          cost: { label: "Fuel", eur: 30 },
          mapsUrl: "https://maps.google.com/?q=Keflavik+International+Airport",
          category: "transport",
          warning: "Fill fuel tank at Olis before returning car",
        },
        {
          id: "d5-flight",
          time: "~09:00",
          icon: "✈️",
          name: "Check in · KEF → AMS → BER",
          note: "HV 6888 → KL 1785. Arrive check-in desk 2h before departure.",
          tags: ["HV 6888 → KL 1785"],
          cost: null,
          mapsUrl: null,
          category: "transport",
        },
      ],
      auroraSpot: null,
    },
  ];
  
  export const COST_SUMMARY = {
    breakdown: [
      { label: "Lava Tunnel + Aurora Tour", amount: 414, note: "~$207/person, pre-paid (≈€190/person)" },
      { label: "Sky Lagoon Saman (x2)", amount: 134, note: "Pre-book at skylagoon.com" },
      { label: "Hallgrímskirkja Tower (x2)", amount: 20, note: "€10/person, paid on-site" },
      { label: "Kerið Crater entry (x2)", amount: 8, note: "€4/person, kiosk" },
      { label: "Parking (4 days total)", amount: 52, note: "Parka + EasyPark + Checkit.is" },
      { label: "DC-3 Shuttle (x2 return)", amount: 56, note: "€14/way × 2 people, or walk free" },
      { label: "Dinners (est. 4 evenings)", amount: 110, note: "Vegetarian, budget restaurants" },
      { label: "Lunches on road (3 days)", amount: 55, note: "Soup stops, cafes" },
      { label: "Cafes + pastries", amount: 48, note: "Brauð & Co, Sandholt, Loo.koo.mas, Sweet Aurora" },
      { label: "Snacks + supermarket", amount: 30, note: "Bónus supermarket" },
      { label: "Fuel for KEF", amount: 30, note: "Olis station Keflavík" },
    ],
  };