export const TRIP_INFO = {
  departureDate: "2026-12-09",
  returnDate: "2026-12-13",
  dates: "Dec 9–13, 2026",
  travellers: 2,
  car: "Toyota Yaris Cross 4x4 Hybrid Automatic",
  carFuel: "Petrol hybrid — fill 95 unleaded. ~20–22 km/litre. Never plug in — charges itself while driving.",
  carCost: "€287 · Full zero-excess coverage included",
  carWifi: "Free 4G WiFi included — keep device charged via USB in car",
  carInsurance: "Zero excess · SCDW · Gravel · Sand & Ash · Tire · Animal · F-Road · River · Theft · 24/7 Roadside",
  carFuelStops: "Day 1: Fill FULL at N1 Keflavík on arrival · Day 3: Fill FULL at N1 Selfoss after Kerið (before South Coast day) · Day 4: Top up at N1 Vík (comfort stop) · Day 5: Fill at Olis Keflavík before car return",
  hotel: "Hotel 201, Kópavogur",
  hotelPhone: "+354 556 1100",
  hotelAddress: "Hliðasmári 5, 200 Kópavogur",
  breakfast: "Included at hotel",
};

export const AURORA_LINKS = [
  { label: "Aurora forecast", url: "https://en.vedur.is/weather/forecasts/aurora/", desc: "Icelandic Met Office — most accurate" },
  { label: "Cloud cover map", url: "https://en.vedur.is/weather/forecasts/elements/#type=CC", desc: "Check for clear skies before heading out" },
  { label: "KP index live", url: "https://www.spaceweatherlive.com/en/solar-activity/kp-index.html", desc: "KP ≥ 3 + clear sky = go out! KP ≥ 5 = city visible" },
  { label: "Grótta tide times", url: "https://www.saeferdin.is/", desc: "Check before walking to lighthouse — floods at high tide" },
];

export const WEATHER_LINKS = [
  { label: "South Coast weather", url: "https://en.vedur.is/weather/forecasts/areas/#area=south", desc: "Day 4 — Vík, Reynisfjara, glacier area" },
  { label: "Golden Circle weather", url: "https://en.vedur.is/weather/forecasts/areas/#area=southwest", desc: "Day 3 — Þingvellir, Geysir, Gullfoss" },
  { label: "Reykjavík weather", url: "https://en.vedur.is/weather/forecasts/areas/#area=capital", desc: "Days 1, 2 — city area" },
  { label: "Road conditions (Vegagerdin)", url: "https://www.road.is/travel-info/road-conditions-and-weather/", desc: "CRITICAL — check every morning before driving" },
  { label: "Road closures map", url: "https://www.road.is/travel-info/road-conditions-and-weather/road-conditions-map/", desc: "Live map of closures + hazards" },
  { label: "Safe Travel Iceland", url: "https://safetravel.is/", desc: "Register trip + emergency contacts" },
];

export const DAILY_ROUTES = {
  1: { label: "Day 1 — Hotel → Loving Hut → Lava Tunnel pickup", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Loving+Hut+Laugavegur+Reykjavik/Raufarholshellir+Lava+Tunnel+Iceland" },
  2: { label: "Day 2 — Old Harbour → Church → City → Sky Lagoon → Grótta", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Sun+Voyager+Reykjavik/Reykjavik+Rost+Harbour/Hallgrimskirkja+Reykjavik/Braud+and+Co+Bakery+Reykjavik/Metal+Design+Reykjavik/Sandholt+Bakery+Laugavegur/Sky+Lagoon+Reykjavik/Grotta+Lighthouse+Seltjarnarnes" },
  3: { label: "Day 3 — Golden Circle + Faxafoss", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Thingvellir+National+Park/Geysir+Geothermal+Area/Faxafoss+Faxi+Waterfall+Iceland/Gullfoss+Waterfall/Kerid+Crater/Kleifarvatn+Lake/Hotel+201+Kopavogur" },
  4: { label: "Day 4 — South Coast: waterfalls, glacier, arch, beach", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Seljalandsfoss/Nauthusagil+Gorge+Iceland/Skogafoss+Iceland/Kvernufoss+Waterfall+Skogar/Vik+Iceland/Solheimajokull+Glacier/Dyrholaey+Lighthouse+Iceland/Reynisfjara+Black+Sand+Beach/Hotel+201+Kopavogur" },
  5: { label: "Day 5 — Hotel → KEF Airport", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Keflavik+International+Airport+Iceland" },
};

export const BOOKINGS = [
  { id: "b1", label: "Outbound flights", detail: "KL 1770 + HV 6887 · BER→AMS→KEF · Dec 9", category: "flight", confirmationKey: "flight_out", linkKey: "flight_out_link", booked: true },
  { id: "b2", label: "Return flights", detail: "HV 6888 + KL 1785 · KEF→AMS→BER · Dec 13", category: "flight", confirmationKey: "flight_ret", linkKey: "flight_ret_link", booked: true },
  { id: "b3", label: "Hotel 201", detail: "Dec 9–13 · 4 nights · Breakfast included", category: "hotel", confirmationKey: "hotel_conf", linkKey: "hotel_link", booked: true },
  { id: "b4", label: "Toyota Yaris Cross 4x4 Hybrid", detail: "€287 · Pick up & drop KEF · Dec 9–13 · Free 4G WiFi · Full zero-excess coverage", category: "car", confirmationKey: "car_conf", linkKey: "car_link", booked: false },
  { id: "b5", label: "Lava Tunnel + NL Tour", detail: "adventures.is · Pickup 19:30 Dec 9 · ~€190/person", category: "tour", confirmationKey: "tour_conf", linkKey: "tour_link", url: "https://adventures.is/iceland/day-tours/caving/lava-tunnel-and-northern-lights/", booked: true },
  { id: "b6", label: "Sky Lagoon — Saman", detail: "14:00 slot · Dec 10 · ~€67/person", category: "spa", confirmationKey: "lagoon_conf", linkKey: "lagoon_link", url: "https://www.skylagoon.com", booked: false },
];

export const PACK_LIST = [
  { id: "pk1", label: "Thermal base layers (top + bottom)", category: "clothing" },
  { id: "pk2", label: "Fleece mid-layer", category: "clothing" },
  { id: "pk3", label: "Waterproof windproof outer jacket", category: "clothing" },
  { id: "pk4", label: "Waterproof trousers / ski pants", category: "clothing" },
  { id: "pk5", label: "Wool socks (x3 pairs)", category: "clothing" },
  { id: "pk6", label: "Waterproof hiking boots / shoes", category: "clothing" },
  { id: "pk7", label: "Warm hat covering ears", category: "clothing" },
  { id: "pk8", label: "Neck gaiter / balaclava", category: "clothing" },
  { id: "pk9", label: "Thermal gloves + waterproof outer gloves", category: "clothing" },
  { id: "pk10", label: "Sunglasses (snow glare)", category: "clothing" },
  { id: "pk11", label: "Camera + extra batteries (cold drains them)", category: "gear" },
  { id: "pk12", label: "Power bank (large, min 20,000 mAh)", category: "gear" },
  { id: "pk13", label: "Micro USB + USB-C cables", category: "gear" },
  { id: "pk14", label: "Universal EU adapter", category: "gear" },
  { id: "pk15", label: "Head torch + extra AAA batteries", category: "gear" },
  { id: "pk16", label: "Tripod for aurora photos", category: "gear" },
  { id: "pk17", label: "Phone waterproof case", category: "gear" },
  { id: "pk18", label: "Thermos flask (1L)", category: "gear" },
  { id: "pk19", label: "Parka app (+ EasyPark) — add plate on arrival", category: "apps" },
  { id: "pk20", label: "Checkit.is bookmarked", category: "apps" },
  { id: "pk21", label: "vedur.is aurora page bookmarked", category: "apps" },
  { id: "pk22", label: "road.is bookmarked", category: "apps" },
  { id: "pk23", label: "saeferdin.is bookmarked (Grótta tides)", category: "apps" },
  { id: "pk24", label: "Google Maps offline — download Iceland map", category: "apps" },
  { id: "pk25", label: "Travel insurance documents", category: "docs" },
  { id: "pk26", label: "Passports (valid 6+ months)", category: "docs" },
  { id: "pk27", label: "European Health Insurance Card (EHIC)", category: "docs" },
  { id: "pk28", label: "Driving licence (both drivers)", category: "docs" },
  { id: "pk29", label: "Credit card (no foreign fees)", category: "docs" },
  { id: "pk30", label: "Cash ISK (small amount — most places card only)", category: "docs" },
  { id: "pk31", label: "Lip balm + moisturiser (wind chapping)", category: "health" },
  { id: "pk32", label: "Hand warmers (disposable, pack of 10)", category: "health" },
  { id: "pk33", label: "Any prescription medication", category: "health" },
  { id: "pk34", label: "Blister plasters (lots of walking)", category: "health" },
  { id: "pk35", label: "Snacks for the car (nuts, energy bars)", category: "food" },
];

export const DAYS = [
  // ── DAY 1 — ARRIVAL + LAVA TUNNEL ─────────────────────────────────────────
  {
    id: 1,
    date: "Tue Dec 9",
    title: "Arrival + Lava Tunnel & Northern Lights",
    badge: "Light day • Tour night",
    badgeColor: "#EEEDFE", badgeText: "#3C3489",
    kmDriving: 60, parkingEur: 0, walkingKm: "Minimal — rest day", routeKey: 1,
    stops: [
      {
        id: "d1s1", time: "14:30", icon: "✈️", name: "Arrive KEF · Collect Toyota Yaris Cross",
        note: "4AM start from Berlin — take it easy. Drive ~45 min to Hotel 201. Register rental plate in Parka + EasyPark apps at the car counter. Ask for N1 fuel discount chip at pickup.",
        tags: ["~45 min to hotel", "Ask for N1 chip at pickup"],
        parking: "Hotel 201 — free on-site parking, large lot, no time limit",
        parkingMapsUrl: "https://maps.google.com/?q=Hotel+201+Kopavogur+parking",
        cost: null, mapsUrl: "https://maps.google.com/?q=Keflavik+International+Airport", category: "transport",
      },
      {
        id: "d1s1b", time: "15:00", icon: "⛽", name: "Fill up — N1 Keflavík (on way to hotel)",
        note: "Fill the tank on your way from KEF to the hotel. Use Lotus N1 chip on reader before inserting Wise card. Select ISK not EUR. 95 unleaded petrol (green nozzle).",
        tags: ["N1 station · Use Lotus chip", "95 unleaded · green nozzle", "Wise card · select ISK", "~€20–25 to fill"],
        parking: "N1 station forecourt — pull up to any pump, no parking fee",
        parkingMapsUrl: "https://maps.google.com/?q=N1+petrol+station+Keflavik+Iceland",
        cost: 25, mapsUrl: "https://maps.google.com/?q=N1+petrol+station+Keflavik+Iceland", category: "transport",
      },
      {
        id: "d1s2", time: "16:30", icon: "🍜", name: "Dinner — Loving Hut",
        note: "Fully vegan Asian restaurant. Big soups, noodles, generous portions. ~20 min from hotel. Open until 9pm. Eat well before the long evening tour.",
        tags: ["100% vegan", "€12–15/person", "4.7★ · 469 reviews"],
        parking: "P1/P2 street parking on Laugavegur — ~€4/hr · Parka or EasyPark. Or park at Hotel 201 (free) and taxi in (~€10, 20 min).",
        parkingMapsUrl: "https://maps.google.com/?q=Laugavegur+164+Reykjavik",
        cost: 30, mapsUrl: "https://maps.google.com/?q=Loving+Hut+Laugavegur+Reykjavik", category: "food",
      },
      {
        id: "d1s3", time: "18:30", icon: "🛋️", name: "Rest at hotel · Layer up",
        note: "Charge camera batteries + power banks. Thermal base layer + fleece + windproof outer. Be at pickup point 15 min early.",
        tags: ["Pickup: central Reykjavík", "Be there by 19:15"],
        parking: "Hotel 201 — free on-site parking. Leave car here — tour bus handles all transport tonight.",
        parkingMapsUrl: "https://maps.google.com/?q=Hotel+201+Kopavogur+Iceland",
        cost: null, mapsUrl: null, category: "rest",
      },
      {
        id: "d1s4", time: "19:30", icon: "🌌", name: "Lava Tunnel & Northern Lights Tour",
        note: "Bus picks up 19:30 from central Reykjavík. Visit Raufarhólshellir lava cave + aurora chasing in dark countryside. Helmets, headlamps & hot drinks included. ~4–5h, back ~midnight. Free re-try if no aurora!",
        tags: ["adventures.is · Pre-booked", "Free re-try guaranteed"],
        parking: "Leave car at Hotel 201. Taxi to pickup (~€10) or hotel bus stop. Tour bus handles all transport.",
        parkingMapsUrl: "https://maps.google.com/?q=Hotel+201+Kopavogur+Iceland",
        cost: null, mapsUrl: "https://maps.google.com/?q=Raufarholshellir+Lava+Tunnel+Iceland", category: "aurora",
      },
    ],
    aurora: { name: "Tour handles aurora tonight", note: "Guide monitors forecast + drives to best location. Nothing to plan — just enjoy.", free: true },
  },

  // ── DAY 2 — REYKJAVÍK CITY + SKY LAGOON (easy recovery day after late night) ──
  {
    id: 2,
    date: "Wed Dec 10",
    title: "Reykjavík · Hallgrímskirkja · Sky Lagoon",
    badge: "Easy day • Recovery + Spa",
    badgeColor: "#FBEAF0", badgeText: "#72243E",
    kmDriving: 35, parkingEur: 5, walkingKm: "3–4 km city walking", routeKey: 2,
    stops: [
      {
        id: "d2c1", time: "09:30", icon: "☕", name: "Slow breakfast at Hotel 201 (included) · No rush",
        note: "Back from tour ~midnight — sleep in and recover. No need to rush today. City day is gentle: short drives, flat city walking, Sky Lagoon to relax. Leave hotel when you're ready, no earlier than 09:30.",
        tags: ["Breakfast included", "Recover from late night", "No early start needed"],
        parking: "Hotel 201 — free on-site parking. Drive to Old Harbour area first.",
        parkingMapsUrl: "https://maps.google.com/?q=Hotel+201+Kopavogur+Iceland",
        cost: null, mapsUrl: null, category: "food",
      },
      {
        id: "d2c2", time: "10:00", icon: "⚓", name: "Old Harbour + Tryggvagata + Sun Voyager",
        note: "Walk the Old Harbour area — Sun Voyager sculpture, Harpa Concert Hall glass facade, Tryggvagata 19 (Kolaportið market building). Allow 30–40 min.",
        tags: ["Free entry", "Harpa Concert Hall", "Sun Voyager sculpture"],
        parking: "🅿️ Kolaport Parking Garage (Kalkofnsvegur 3) — rated 4.8★, cheapest near harbour, underground, right across from Harpa. ~€1.40/hr · Open 7am–midnight · Pay Parka or EasyPark",
        parkingMapsUrl: "https://maps.google.com/?q=Kolaport+parking+garage+Kalkofnsvegur+Reykjavik",
        cost: null, walking: "~1 km flat harbour walk",
        mapsUrl: "https://maps.google.com/?q=Sun+Voyager+sculpture+Reykjavik", category: "sightseeing",
      },
      {
        id: "d2c3", time: "10:30", icon: "☕", name: "☕ Reykjavík Röst — harbour café",
        note: "Right at the Old Harbour. Café with sourdough sandwiches, homemade cakes, excellent coffee and vegan options. Quiet spot with scenic views over the marina.",
        tags: ["Vegan options ✓", "Harbour views", "Homemade cakes"],
        parking: "🅿️ Still at Kolaport Garage — no need to move car.",
        parkingMapsUrl: "https://maps.google.com/?q=Kolaport+parking+garage+Kalkofnsvegur+Reykjavik",
        cost: 18, mapsUrl: "https://maps.google.com/?q=Reykjavik+Rost+harbour+cafe", category: "cafe",
      },
      {
        id: "d2c4", time: "11:15", icon: "⛪", name: "Hallgrímskirkja Church + Tower",
        note: "Move car to Bergstaðarstræti Garage (10 min drive). Opens 10am in winter. Elevator to tower — 360° panoramic views. Church interior free. Tower entry on-site. Allow 45–60 min.",
        tags: ["Church: free", "Tower: €10/person", "4.6★ · 28,272 reviews", "Opens 10am in winter"],
        parking: "🅿️ Bergstaðarstræti Parking (Bergstaðarstræti 9) — closest garage to church, open 24/7. OR free street parking on Njarðargata / Bárugata south of church. ~€1.40/hr · Parka or EasyPark",
        parkingMapsUrl: "https://maps.google.com/?q=Bergstadastraeti+parking+lot+Reykjavik",
        cost: 25, walking: "~0.1 km · elevator to tower",
        mapsUrl: "https://maps.google.com/?q=Hallgrimskirkja+church+Reykjavik", category: "sightseeing",
      },
      {
        id: "d2c5", time: "12:15", icon: "🥐", name: "☕ Brauð & Co — legendary cinnamon bun",
        note: "Steps from the church on Frakkastígur. Iceland's most famous bakery. Cinnamon rolls are world-class. Ask for Kleinur — December-only Christmas pastry.",
        tags: ["4.8★ · 4,719 reviews", "€4–6/item", "Ask for Kleinur 🍩 — December only"],
        parking: "🅿️ Same Bergstaðarstræti garage — 2-min walk. No need to move car.",
        parkingMapsUrl: "https://maps.google.com/?q=Bergstadastraeti+parking+lot+Reykjavik",
        cost: 14, walking: "~0.1 km from church",
        mapsUrl: "https://maps.google.com/?q=Braud+and+Co+bakery+Reykjavik", category: "cafe",
      },
      {
        id: "d2c6", time: "12:30", icon: "💎", name: "Jewellery — Metal Design + Orrifinn backup",
        note: "Metal Design (Skólavörðustígur 2) — handmade silver & lava jewellery, owner-run, hours unreliable. BACKUP: Orrifinn Jewels (No. 43, same street) — voted Best Jewellery in Reykjavík, always reliable.",
        tags: ["Metal Design: No. 2", "Orrifinn backup: No. 43", "⚠️ Metal Design hours unreliable", "€20–100+"],
        parking: "🅿️ Still at Bergstaðarstræti garage — Rainbow Street is a 3-min downhill walk from church.",
        parkingMapsUrl: "https://maps.google.com/?q=Bergstadastraeti+parking+lot+Reykjavik",
        cost: 40, walking: "~0.5 km walk down Rainbow Street",
        warning: "Metal Design may be closed — Orrifinn Jewels at No. 43 is the reliable backup",
        mapsUrl: "https://maps.google.com/?q=Metal+Design+Skolavordustigur+2+Reykjavik", category: "sightseeing",
      },
      {
        id: "d2c7", time: "12:45", icon: "🌈", name: "Skólavörðustígur (Rainbow Street) + Laugavegur shopping",
        note: "Walk down Rainbow Street to Laugavegur — Reykjavík's main shopping strip. Browse Lopapeysa wool sweaters, lava jewellery, bookshops, Icelandic candy. Allow 1–1.5h.",
        tags: ["Walking — no driving needed", "Lopapeysa wool sweaters", "Icelandic candy"],
        parking: "🅿️ Still at Bergstaðarstræti garage — Laugavegur is 5-min downhill. One park covers the ENTIRE morning.",
        parkingMapsUrl: "https://maps.google.com/?q=Bergstadastraeti+parking+lot+Reykjavik",
        cost: null, walking: "~1 km Rainbow Street + Laugavegur combined",
        mapsUrl: "https://maps.google.com/?q=Skolavordustigur+Rainbow+Street+Reykjavik", category: "sightseeing",
      },
      {
        id: "d2c8", time: "13:30", icon: "🧆", name: "Lunch — Chickpea (4.9★) or 101 Street Food",
        note: "Chickpea: falafel wraps, hummus, kimchi. ~€11. Or 101 Street Food: veggie soup + unlimited bread ~€8–10. Both near Laugavegur. Wednesday — both open.",
        tags: ["Vegetarian ✓", "4.9★ Chickpea", "€8–13/person", "Wednesday — both open"],
        parking: "🅿️ Still at Bergstaðarstræti garage. After lunch, collect car and drive to Sky Lagoon.",
        parkingMapsUrl: "https://maps.google.com/?q=Bergstadastraeti+parking+lot+Reykjavik",
        cost: 24, mapsUrl: "https://maps.google.com/?q=Chickpea+restaurant+Reykjavik", category: "food",
      },
      {
        id: "d2c9", time: "14:15", icon: "☕", name: "☕ Sandholt Bakery — coffee & cream puffs",
        note: "Laugavegur 36. Family-run since the 1920s. Famous cream puffs, Danish pastries, oat latte. On the walk back to collect the car.",
        tags: ["4.6★ · 4,285 reviews", "€5–8/item", "Open 7:30am–6pm"],
        parking: "🅿️ On the walk BACK to Bergstaðarstræti garage.",
        parkingMapsUrl: "https://maps.google.com/?q=Bergstadastraeti+parking+lot+Reykjavik",
        cost: 20, mapsUrl: "https://maps.google.com/?q=Sandholt+bakery+Laugavegur+Reykjavik", category: "cafe",
      },
      {
        id: "d2c10", time: "15:00", icon: "🌊", name: "Sky Lagoon — sunset & blue hour",
        note: "5 min drive from Hotel 201. Arrive 15:00 to catch sunset (~15:30) from the infinity edge over the Atlantic. Saman package: lagoon → cold pool → sauna → cold mist → sky bath → steam → salt scrub + shower. ⚠️ Shower WITHOUT swimsuit before entering — strictly enforced. Open until 11pm.",
        tags: ["Pre-book: skylagoon.com", "Saman ~€67/person", "4.7★ · 9,018 reviews", "⚠️ Shower without swimsuit first"],
        parking: "🅿️ FREE large on-site car park at Sky Lagoon — no time limit, no charge.",
        parkingMapsUrl: "https://maps.google.com/?q=Sky+Lagoon+Reykjavik+parking",
        cost: 134, mapsUrl: "https://maps.google.com/?q=Sky+Lagoon+Reykjavik", category: "spa",
      },
      {
        id: "d2c11", time: "18:00", icon: "🍜", name: "Dinner — Loving Hut",
        note: "Asian soups + noodles, big portions. ~€12–15/person. Open until 9pm. Early night — big driving day tomorrow.",
        tags: ["Vegan ✓", "€12–15/person", "Early night — big day tomorrow"],
        parking: "🅿️ Street parking on Laugavegur — P1/P2 zone ~€4/hr · Parka. After 9pm FREE.",
        parkingMapsUrl: "https://maps.google.com/?q=Laugavegur+street+parking+Reykjavik",
        cost: 30, mapsUrl: "https://maps.google.com/?q=Loving+Hut+Laugavegur+Reykjavik", category: "food",
      },
      {
        id: "d2c12", time: "19:30", icon: "🍩", name: "☕ Loo.koo.mas — Greek donuts & hot chocolate",
        note: "Laugavegur 30a. 4.9★ — highest rated sweet spot in Reykjavík. Greek loukoumades (honey donuts) + hot chocolate. Then home to bed early — South Coast tomorrow needs an 09:00 start.",
        tags: ["4.9★ · 1,560 reviews", "€6–9/portion", "Early night after this!"],
        parking: "🅿️ Same Laugavegur street parking. After 9pm it's FREE.",
        parkingMapsUrl: "https://maps.google.com/?q=Laugavegur+street+parking+Reykjavik",
        cost: 16, mapsUrl: "https://maps.google.com/?q=Lookumas+Laugavegur+Reykjavik", category: "cafe",
      },
    ],
    aurora: {
      name: "Grótta Lighthouse — 15 min from hotel",
      note: "If you have energy after Sky Lagoon, Grótta is the best close-to-city aurora spot. But don't push it — big South Coast day tomorrow needs good rest. Only go if KP ≥ 4 and skies are clear.",
      parking: "Free roadside parking at Seltjarnarnes tip — large gravel area at the end of Nesvegur road. No app, no fee. GPS: 64.1650°N, 22.0220°W",
      parkingMapsUrl: "https://maps.google.com/?q=Grotta+Lighthouse+Seltjarnarnes+parking",
      free: true,
    },
  },

  // ── DAY 3 — GOLDEN CIRCLE + FAXAFOSS ──────────────────────────────────────
  {
    id: 3,
    date: "Thu Dec 11",
    title: "Golden Circle + Faxafoss",
    badge: "Full day • 280 km",
    badgeColor: "#E6F1FB", badgeText: "#0C447C",
    kmDriving: 280, parkingEur: 28, walkingKm: "3–4 km total", routeKey: 3,
    stops: [
      {
        id: "d3s1", time: "08:30", icon: "☕", name: "Breakfast at Hotel 201 (included) · Depart 09:30",
        tags: ["Breakfast included", "⛽ Check fuel — top up at N1 Selfoss if below half"],
        parking: "Hotel 201 — free on-site parking.",
        parkingMapsUrl: "https://maps.google.com/?q=Hotel+201+Kopavogur+Iceland",
        cost: null, mapsUrl: null, category: "food",
      },
      {
        id: "d3s2", time: "10:15", icon: "🌋", name: "Þingvellir National Park",
        note: "45 min drive. Walk the Almannagjá gorge between North American & Eurasian tectonic plates. Iceland's parliament site 930 AD. UNESCO World Heritage. Allow 1–1.5h.",
        tags: ["Free entry", "UNESCO", "4.7★ · 24,206 reviews"],
        parking: "Þingvellir Parking P1 (Hakið viewpoint) — most popular lot, closest to gorge entrance. €7 (1,000 ISK) · Checkit.is · Valid ALL lots all day.",
        parkingMapsUrl: "https://maps.google.com/?q=Thingvellir+P1+parking+Iceland",
        cost: 7, walking: "~1.5 km flat gorge walk",
        mapsUrl: "https://maps.google.com/?q=Thingvellir+National+Park+Iceland", category: "nature",
      },
      {
        id: "d3s3", time: "12:00", icon: "♨️", name: "Geysir Geothermal Area",
        note: "45 min from Þingvellir. Strokkur erupts every 5–10 min — keep camera ready! Geysir Bistro has hot vegetable soup. Allow 1h.",
        tags: ["Free entry", "4.7★ · 4,702 reviews", "Soup at Geysir Bistro"],
        parking: "Geysir Car Park — large paved lot right at entrance. €7 (1,000 ISK) · Parka app.",
        parkingMapsUrl: "https://maps.google.com/?q=Geysir+car+park+Iceland",
        cost: 21, walking: "~0.5 km flat paved area",
        mapsUrl: "https://maps.google.com/?q=Geysir+geothermal+area+Iceland", category: "nature",
      },
      {
        id: "d3s4", time: "13:20", icon: "🐴", name: "Faxafoss Waterfall (Faxi)",
        note: "11 km south of Geysir on Route 35. Follow signs for 'Við Faxa'. Wide, calm, peaceful — 80m across. Salmon fish ladder alongside. Almost no crowds. Allow 20–25 min.",
        tags: ["Free entry", "Hidden gem on Golden Circle", "Almost no crowds"],
        parking: "Faxafoss Car Park — small dedicated lot right at waterfall, well signed from Route 35. €6 (900 ISK) · Pay machine on-site (card accepted).",
        parkingMapsUrl: "https://maps.google.com/?q=Faxafoss+Faxi+waterfall+parking+Iceland",
        cost: 6, walking: "~0.3 km flat to viewpoint",
        mapsUrl: "https://maps.google.com/?q=Faxafoss+waterfall+Faxi+Iceland", category: "nature",
      },
      {
        id: "d3s5", time: "14:10", icon: "💧", name: "Gullfoss Waterfall",
        note: "9 km from Faxafoss. Two-tier cascade into a canyon. December spray freezes into ice sculptures. Gullfoss café on site. Allow 45 min.",
        tags: ["Free entry", "FREE parking", "4.9★ · 5,559 reviews"],
        parking: "Gullfoss Car Park — completely FREE large paved lot. No app, no payment needed. Café and toilets on-site.",
        parkingMapsUrl: "https://maps.google.com/?q=Gullfoss+car+park+Iceland",
        cost: null, walking: "~0.8 km to upper and lower viewpoints",
        mapsUrl: "https://maps.google.com/?q=Gullfoss+waterfall+Iceland", category: "nature",
      },
      {
        id: "d3s6", time: "15:15", icon: "⭕", name: "Kerið Volcanic Crater",
        note: "~55 min south. Vivid red-and-green crater with a lake inside. Walk the rim at last light or descend to the floor. Entry at gate kiosk. Allow 30–40 min.",
        tags: ["Entry: €4/person at kiosk", "4.5★ · 19,973 reviews"],
        parking: "Kerið Car Park — free parking at entrance gate. Entry fee (€4/person) paid at kiosk — card accepted. Parking itself always free.",
        parkingMapsUrl: "https://maps.google.com/?q=Kerid+crater+car+park+Iceland",
        cost: 8, walking: "~0.8 km rim walk · optional descent to crater floor",
        mapsUrl: "https://maps.google.com/?q=Kerid+volcanic+crater+Iceland", category: "nature",
      },
      {
        id: "d3s6b", time: "16:15", icon: "⛽", name: "⛽ Fill up — N1 Selfoss (on way back to Reykjavík)",
        note: "IMPORTANT — top up here before tomorrow's South Coast day. After 280 km today your tank will be at ~55–60%. Day 4 South Coast is 390 km with only one remote fuel stop (Vík). Starting Day 4 with a FULL tank means the Vík stop is a comfort top-up, not an emergency. N1 Selfoss is right on Route 1 on your way back — takes 5 minutes. Use Lotus N1 chip + Wise card. Select ISK.",
        tags: ["⛽ Fill before South Coast day", "N1 Selfoss · Route 1", "Use Lotus chip", "Wise card · select ISK"],
        parking: "N1 Selfoss forecourt — pull up to any pump. On Route 1 westbound, well signed.",
        parkingMapsUrl: "https://maps.google.com/?q=N1+petrol+station+Selfoss+Iceland",
        cost: 15, mapsUrl: "https://maps.google.com/?q=N1+petrol+station+Selfoss+Iceland",
        category: "transport",
        warning: "Don't skip — ensures you start Day 4 South Coast with a full tank",
      },
      {
        id: "d3s7", time: "17:30", icon: "🍜", name: "Dinner — Loving Hut or Chickpea",
        note: "Back in Reykjavík ~17:00. Loving Hut for Asian soups or Chickpea for falafel wraps. Both ~€10–15/person.",
        tags: ["Vegetarian ✓", "€10–15/person"],
        parking: "P1/P2 street parking on Laugavegur — ~€4/hr · Parka or EasyPark. After 21:00 FREE.",
        parkingMapsUrl: "https://maps.google.com/?q=Laugavegur+street+parking+Reykjavik",
        cost: 28, mapsUrl: "https://maps.google.com/?q=Chickpea+Reykjavik", category: "food",
      },
    ],
    aurora: {
      name: "Kleifarvatn Lake (40 min) or Heiðmörk Reserve (20 min)",
      note: "Head out ~19:30 after dinner. Kleifarvatn: volcanic lake, hills block city glow, water reflects lights beautifully. Heiðmörk: dark lava park, only 20 min away. Good rest after — South Coast tomorrow.",
      parking: "Kleifarvatn: free roadside pull-off on Route 42 beside the lake. GPS: 63.9257°N, 21.9716°W · Heiðmörk: free parking at reserve entrance on Elliðavatnsvegur.",
      parkingMapsUrl: "https://maps.google.com/?q=Kleifarvatn+Lake+parking+Iceland",
      free: true,
    },
  },

  // ── DAY 4 — SOUTH COAST (now with full energy!) ────────────────────────────
  {
    id: 4,
    date: "Fri Dec 12",
    title: "South Coast — Waterfalls, Glacier & Black Beach",
    badge: "Big day • 390 km",
    badgeColor: "#E6F1FB", badgeText: "#0C447C",
    kmDriving: 390, parkingEur: 28, walkingKm: "4–5 km total", routeKey: 4,
    stops: [
      {
        id: "d4s1", time: "08:00", icon: "☕", name: "Breakfast at Hotel 201 (included) · Depart 09:00",
        note: "Biggest driving day — fully rested after 3 nights. Pack thermos + snacks from Bónus. Leave by 09:00 sharp to make the most of 4.5h daylight. Check road.is before leaving.",
        tags: ["Breakfast included", "⛽ Tank ~70% from Day 3 — fill at N1 Vík after lunch", "Check road.is before leaving"],
        parking: "Hotel 201 — free on-site parking. Car parked here overnight.",
        parkingMapsUrl: "https://maps.google.com/?q=Hotel+201+Kopavogur+Iceland",
        cost: null, mapsUrl: null, category: "food",
      },
      {
        id: "d4s2", time: "10:40", icon: "💧", name: "Seljalandsfoss Waterfall",
        note: "Walk behind the waterfall curtain — magical in winter but path can close if too icy. Also visit nearby Gljúfrabúi hidden waterfall (5 min walk). Allow 40–45 min.",
        tags: ["Free entry", "4.8★ · 3,418 reviews", "1h 40min from hotel"],
        parking: "Seljalandsfoss Car Park — large dedicated lot right at the waterfall. €7 (1,000 ISK) · Checkit.is or card kiosk · Valid all day.",
        parkingMapsUrl: "https://maps.google.com/?q=Seljalandsfoss+parking+lot+Iceland",
        cost: 7, walking: "~0.8 km flat loop",
        mapsUrl: "https://maps.google.com/?q=Seljalandsfoss+waterfall+Iceland",
        category: "nature", warning: "Icy path possible — waterproof shoes essential",
      },
      {
        id: "d4s2b", time: "11:30", icon: "🪨", name: "Nauthúsagil Gorge — hidden gem",
        note: "5 min drive on Route 249. Walk inside the gorge over stones with chains for support. Hidden waterfall at the end. December stream may be partially frozen. Almost nobody visits this.",
        tags: ["Free entry", "Almost no crowds", "~5 min from Seljalandsfoss"],
        parking: "Free roadside pull-off on Route 249 — small gravel area on the left. No fee, no app. GPS: 63.6207°N, 19.9782°W",
        parkingMapsUrl: "https://maps.google.com/?q=Nauthusagil+gorge+parking+Iceland",
        cost: null, walking: "~1 km each way · slippery stones · chains for support",
        mapsUrl: "https://maps.google.com/?q=Nauthusagil+gorge+Iceland",
        category: "nature", warning: "Stepping stones in stream — waterproof boots essential",
      },
      {
        id: "d4s3", time: "12:20", icon: "💧", name: "Skógafoss Waterfall",
        note: "20 min east. Iceland's most photogenic waterfall. Climb the staircase for elevated views. Winter spray freezes beautifully. Allow 40 min.",
        tags: ["Free entry", "4.9★ · 4,379 reviews"],
        parking: "Skógafoss Car Park — large lot at the waterfall base. €7 (1,000 ISK) · Parka location 8205 · 8h valid. Same ticket covers Kvernufoss visit.",
        parkingMapsUrl: "https://maps.google.com/?q=Skogafoss+car+park+Iceland",
        cost: 7, walking: "~0.5 km flat to base · optional 370 steps staircase",
        mapsUrl: "https://maps.google.com/?q=Skogafoss+waterfall+Iceland", category: "nature",
      },
      {
        id: "d4s3b", time: "13:05", icon: "🌊", name: "Kvernufoss — secret walk-behind waterfall",
        note: "Same car park as Skógafoss — no extra cost! Walk behind Skógar Museum, follow fence to stairs then path into valley. 15–20 min walk each way. Almost zero crowds. Many say their favourite waterfall in Iceland.",
        tags: ["Free entry", "Same parking as Skógafoss", "Almost no crowds"],
        parking: "Skógafoss Car Park — already paid. Walk from same lot. No need to move car.",
        parkingMapsUrl: "https://maps.google.com/?q=Skogafoss+car+park+Iceland",
        cost: null, walking: "~1.5 km return · mostly flat · 15–20 min each way",
        mapsUrl: "https://maps.google.com/?q=Kvernufoss+waterfall+Iceland", category: "nature",
      },
      {
        id: "d4s4", time: "14:00", icon: "🍲", name: "Lunch — Suður-Vík, Vík village",
        note: "30 min drive east. Best restaurant on the South Coast. Vegetable soup + bread. Open noon–9pm.",
        tags: ["Veggie soup ✓", "4.7★ · 2,856 reviews", "Open noon–9pm"],
        parking: "Free street parking on Víkurbraut (main road through Vík) — no fee, no time limit.",
        parkingMapsUrl: "https://maps.google.com/?q=Sudur+Vik+restaurant+Vik+Iceland",
        cost: 20, mapsUrl: "https://maps.google.com/?q=Sudur+Vik+restaurant+Vik+Iceland", category: "food",
      },
      {
        id: "d4s4b", time: "14:45", icon: "⛽", name: "⛽ Top up — N1 Vík (comfort stop)",
        note: "You started today with a FULL tank (filled at N1 Selfoss yesterday evening). Tank is ~75% here in Vík after 130 km of driving. Still top up here — Sólheimajökull, Dyrhólaey and Reynisfjara have NO petrol stations for the next 45 km of remote road. A quick top-up means zero stress for the rest of the afternoon and aurora evening. Use Lotus N1 chip then Wise card. Select ISK not EUR. Takes 5 min.",
        tags: ["✅ Comfort top-up — not emergency", "N1 Vík · Use Lotus chip", "Wise card · select ISK", "No stations for 45 km ahead"],
        parking: "N1 station forecourt in Vík — pull up to any pump.",
        parkingMapsUrl: "https://maps.google.com/?q=N1+petrol+station+Vik+Iceland",
        cost: 10, mapsUrl: "https://maps.google.com/?q=N1+petrol+station+Vik+Iceland",
        category: "transport",
      },
      {
        id: "d4s5", time: "15:00", icon: "🏔️", name: "Sólheimajökull Glacier",
        note: "15 min west of Vík. Short 10-min flat walk to the glacier tongue. Black volcanic ash on white ice — surreal December scenery. Allow 30–35 min.",
        tags: ["Free entry", "4.9★ · 357 reviews"],
        parking: "Sólheimajökull Car Park — dedicated lot at end of access road. €7 (1,000 ISK) · Parka. Turn off Ring Road at sign 'Sólheimajökull'.",
        parkingMapsUrl: "https://maps.google.com/?q=Solheimajokull+parking+Iceland",
        cost: 7, walking: "~1 km flat return to glacier viewpoint",
        mapsUrl: "https://maps.google.com/?q=Solheimajokull+glacier+Iceland", category: "nature",
      },
      {
        id: "d4s6", time: "15:45", icon: "🌊", name: "Dyrhólaey Arch & Lighthouse",
        note: "20 min drive. 120m natural volcanic arch + lighthouse with panoramic South Coast views. Lower car park for arch, upper for lighthouse. No bird restrictions in December. Allow 40 min.",
        tags: ["Free entry", "Panoramic South Coast views", "No timeslots"],
        parking: "Two free car parks: (1) Dyrhólaey Lower Car Park — arch viewpoint. (2) Lighthouse Car Park — panoramic views. Both completely free, no app needed.",
        parkingMapsUrl: "https://maps.google.com/?q=Dyrholaey+parking+lower+Iceland",
        cost: null, walking: "~0.5 km flat to arch · drive to lighthouse",
        mapsUrl: "https://maps.google.com/?q=Dyrholaey+arch+lighthouse+Iceland", category: "nature",
      },
      {
        id: "d4s7", time: "16:30", icon: "🏖️", name: "Reynisfjara Black Sand Beach",
        note: "10 min from Dyrhólaey. Basalt columns + Reynisdrangar sea stacks. Dark by arrival — use phone torch. Stay for aurora if sky clears.",
        tags: ["Free entry", "4.8★ · 2,440 reviews"],
        parking: "Reynisfjara Car Park — Lower lot (€7/1,000 ISK · Parka loc 8202 · 3h) closest to beach. Upper lot (€5/750 ISK) 200m further back.",
        parkingMapsUrl: "https://maps.google.com/?q=Reynisfjara+parking+lot+Iceland",
        cost: 7, walking: "~0.5 km flat beach walk",
        mapsUrl: "https://maps.google.com/?q=Reynisfjara+black+sand+beach+Iceland",
        category: "nature", warning: "⚠️ DANGER: Rogue waves fatal — stay 30m+ from waterline at all times",
      },
    ],
    aurora: {
      name: "Reynisfjara Beach or Vík outskirts",
      note: "Already there at nightfall. Zero light pollution. Stay if KP ≥ 3 + sky clear. Drive back by 20:30 (2h 30min to hotel).",
      parking: "Reynisfjara Car Park — already there. Lower lot paid · Parka loc 8202. OR Vík: free roadside parking on Víkurbraut facing north.",
      parkingMapsUrl: "https://maps.google.com/?q=Reynisfjara+parking+lot+Iceland",
      free: true,
    },
  },

  // ── DAY 5 — DEPARTURE ─────────────────────────────────────────────────────
  {
    id: 5,
    date: "Sat Dec 13",
    title: "Departure Day",
    badge: "Morning only ✈️",
    badgeColor: "#FAEEDA", badgeText: "#633806",
    kmDriving: 50, parkingEur: 0, walkingKm: "Minimal — airport only", routeKey: 5,
    stops: [
      {
        id: "d5s1", time: "06:30", icon: "☕", name: "Early breakfast + checkout",
        note: "Ask hotel the evening before what time breakfast opens. Pack bags the night before. Leave hotel no later than 07:15 for a 10:00–12:00 departure flight.",
        tags: ["Breakfast included", "⚠️ Leave hotel by 07:15"],
        parking: "Hotel 201 — load bags into car before breakfast.",
        parkingMapsUrl: "https://maps.google.com/?q=Hotel+201+Kopavogur+Iceland",
        cost: null, mapsUrl: null, category: "food", warning: "Leave hotel no later than 07:15",
      },
      {
        id: "d5s2", time: "07:15", icon: "🚗", name: "Drive toward KEF",
        note: "~45 min drive. Fill up at Olis BEFORE reaching Lotus drop-off. Return car to Lotus at Flugvellir 6, 230 Keflavík. Allow 30 min for car return + free shuttle to terminal.",
        tags: ["Fill tank BEFORE car return", "Lotus: Flugvellir 6 Keflavík"],
        parking: "Lotus Car Rental drop-off — Flugvellir 6, 230 Keflavík. Free drop-off bay. Free airport shuttle every 15 min.",
        parkingMapsUrl: "https://maps.google.com/?q=Lotus+Car+Rental+Flugvellir+6+Keflavik+Iceland",
        cost: null, mapsUrl: "https://maps.google.com/?q=Lotus+Car+Rental+Flugvellir+6+Keflavik", category: "transport",
      },
      {
        id: "d5s2b", time: "07:30", icon: "⛽", name: "⛽ Fill up — Olis Keflavík town (BEFORE car return)",
        note: "MUST DO before returning car. Full-to-full policy — return without full tank = premium charge. Olis: Hafnargata 57, Keflavík. 5 min before Lotus office. Wise card + select ISK.",
        tags: ["⚠️ Full-to-full policy", "Olis: Hafnargata 57, Keflavík", "N1 chip if N1 available", "Wise card · select ISK"],
        parking: "Olis Keflavík forecourt — pull up to any pump.",
        parkingMapsUrl: "https://maps.google.com/?q=Olis+petrol+station+Hafnargata+Keflavik+Iceland",
        cost: 15, mapsUrl: "https://maps.google.com/?q=Olis+petrol+station+Keflavik+Iceland",
        category: "transport", warning: "Return car with FULL tank — charged at premium if not filled",
      },
      {
        id: "d5s3", time: "09:00", icon: "✈️", name: "Check in · KEF → AMS → BER",
        note: "HV 6888 → KL 1785. Arrive check-in desk 2h before flight. Lotus shuttle drops at KEF terminal. Enjoy the memories!",
        tags: ["HV 6888 → KL 1785"],
        parking: "Car already returned to Lotus. Free shuttle to terminal.",
        parkingMapsUrl: "https://maps.google.com/?q=Keflavik+International+Airport+Iceland",
        cost: null, mapsUrl: null, category: "transport",
      },
    ],
    aurora: null,
  },
];

export const COST_BREAKDOWN = [
  { label: "Toyota Yaris Cross 4x4 Hybrid rental", eur: 287, note: "Full zero-excess coverage · Free 4G WiFi · Dec 9–13", category: "transport" },
  { label: "Lava Tunnel + Aurora Tour (x2)", eur: 380, note: "Pre-booked · adventures.is", category: "experience" },
  { label: "Sky Lagoon Saman (x2)", eur: 134, note: "Pre-book at skylagoon.com", category: "experience" },
  { label: "Hallgrímskirkja Tower (x2)", eur: 20, note: "€10/person, on-site", category: "sightseeing" },
  { label: "Kerið Crater entry (x2)", eur: 8, note: "€4/person at kiosk", category: "sightseeing" },
  { label: "Parking (4 days incl. Faxafoss)", eur: 58, note: "Parka + EasyPark + Checkit.is + Faxafoss on-site", category: "transport" },
  { label: "Fuel — hybrid (whole trip est.)", eur: 80, note: "Yaris Cross ~20km/litre · Fill at KEF Day 1 + Vík Day 4 + Olis KEF Day 5", category: "transport" },
  { label: "Dinners (est. 4 evenings)", eur: 116, note: "Loving Hut, Chickpea, 101 Street Food", category: "food" },
  { label: "Lunches on road (2 days)", eur: 40, note: "Suður-Vík, Geysir Bistro", category: "food" },
  { label: "Cafes + pastries (Day 2 city walk)", eur: 68, note: "Reykjavík Röst + Brauð & Co + Sandholt + Loo.koo.mas + Kleinur", category: "food" },
  { label: "Metal Design — lava jewellery", eur: 30, note: "Handmade Icelandic lava · Rainbow Street", category: "shopping" },
  { label: "Supermarket snacks (Bónus)", eur: 30, note: "Stock up for road days · ISK cash useful", category: "food" },
];