export const TRIP_INFO = {
  departureDate: "2026-12-09",
  returnDate: "2026-12-13",
  dates: "Dec 9–13, 2026",
  travellers: 2,
  car: "Toyota Yaris Cross 4x4 Hybrid Automatic",
  carFuel: "Petrol hybrid — fill 95 unleaded. ~20–22 km/litre. Never plug in — charges itself while driving.",
  carCost: "€287 · Full zero-excess coverage included",
  carWifi: "Free 4G WiFi included — keep device charged via USB in car",
  carInsurance: "Zero excess · SCDW · Gravel · Sand & Ash · Tire · Animal · F-Road · River · Theft · 24/7 Roadside",
  carFuelStops: "Fill up near KEF on arrival · Fill in Vík on Day 2 before glacier/beach · Fill at Olis Keflavík on departure",
  hotel: "Hotel 201, Kópavogur",
  hotelPhone: "+354 556 1100",
  hotelAddress: "Hliðasmári 5, 200 Kópavogur",
  breakfast: "Included at hotel",
};

export const AURORA_LINKS = [
  { label: "Aurora forecast", url: "https://en.vedur.is/weather/forecasts/aurora/", desc: "Icelandic Met Office — most accurate" },
  { label: "Cloud cover map", url: "https://en.vedur.is/weather/forecasts/elements/#type=CC", desc: "Check for clear skies before heading out" },
  { label: "KP index live", url: "https://www.spaceweatherlive.com/en/solar-activity/kp-index.html", desc: "KP ≥ 3 + clear sky = go out! KP ≥ 5 = city visible" },
  { label: "Grótta tide times", url: "https://www.saeferdin.is/", desc: "Check before walking to lighthouse — floods at high tide" },
];

export const WEATHER_LINKS = [
  { label: "South Coast weather", url: "https://en.vedur.is/weather/forecasts/areas/#area=south", desc: "Day 2 — Vík, Reynisfjara, glacier area" },
  { label: "Golden Circle weather", url: "https://en.vedur.is/weather/forecasts/areas/#area=southwest", desc: "Day 3 — Þingvellir, Geysir, Gullfoss" },
  { label: "Reykjavík weather", url: "https://en.vedur.is/weather/forecasts/areas/#area=capital", desc: "Days 1, 4 — city area" },
  { label: "Road conditions (Vegagerdin)", url: "https://www.road.is/travel-info/road-conditions-and-weather/", desc: "CRITICAL — check every morning before driving" },
  { label: "Road closures map", url: "https://www.road.is/travel-info/road-conditions-and-weather/road-conditions-map/", desc: "Live map of closures + hazards" },
  { label: "Safe Travel Iceland", url: "https://safetravel.is/", desc: "Register trip + emergency contacts" },
];

export const DAILY_ROUTES = {
  1: { label: "Day 1 — Hotel → Loving Hut → Lava Tunnel pickup", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Loving+Hut+Laugavegur+Reykjavik/Raufarholshellir+Lava+Tunnel+Iceland" },
  2: { label: "Day 2 — South Coast: waterfalls, glacier, arch, beach", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Seljalandsfoss/Nauthusagil+Gorge+Iceland/Skogafoss+Iceland/Kvernufoss+Waterfall+Skogar/Vik+Iceland/Solheimajokull+Glacier/Dyrholaey+Lighthouse+Iceland/Reynisfjara+Black+Sand+Beach/Hotel+201+Kopavogur" },
  3: { label: "Day 3 — Golden Circle + Faxafoss", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Thingvellir+National+Park/Geysir+Geothermal+Area/Faxafoss+Faxi+Waterfall+Iceland/Gullfoss+Waterfall/Kerid+Crater/Kleifarvatn+Lake/Hotel+201+Kopavogur" },
  4: { label: "Day 4 — Old Harbour → Church → City → Sky Lagoon → Grótta", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Sun+Voyager+Reykjavik/Reykjavik+Rost+Harbour/Hallgrimskirkja+Reykjavik/Braud+and+Co+Bakery+Reykjavik/Metal+Design+Reykjavik/Sandholt+Bakery+Laugavegur/Sky+Lagoon+Reykjavik/Grotta+Lighthouse+Seltjarnarnes" },
  5: { label: "Day 5 — Hotel → KEF Airport", url: "https://www.google.com/maps/dir/Hotel+201+Kopavogur/Keflavik+International+Airport+Iceland" },
};

export const BOOKINGS = [
  { id: "b1", label: "Outbound flights", detail: "KL 1770 + HV 6887 · BER→AMS→KEF · Dec 9", category: "flight", confirmationKey: "flight_out", linkKey: "flight_out_link", booked: true },
  { id: "b2", label: "Return flights", detail: "HV 6888 + KL 1785 · KEF→AMS→BER · Dec 13", category: "flight", confirmationKey: "flight_ret", linkKey: "flight_ret_link", booked: true },
  { id: "b3", label: "Hotel 201", detail: "Dec 9–13 · 4 nights · Breakfast included", category: "hotel", confirmationKey: "hotel_conf", linkKey: "hotel_link", booked: true },
  { id: "b4", label: "Toyota Yaris Cross 4x4 Hybrid", detail: "€287 · Pick up & drop KEF · Dec 9–13 · Free 4G WiFi · Full zero-excess coverage", category: "car", confirmationKey: "car_conf", linkKey: "car_link", booked: false },
  { id: "b5", label: "Lava Tunnel + NL Tour", detail: "adventures.is · Pickup 19:30 Dec 9 · ~€190/person", category: "tour", confirmationKey: "tour_conf", linkKey: "tour_link", url: "https://adventures.is/iceland/day-tours/caving/lava-tunnel-and-northern-lights/", booked: true },
  { id: "b6", label: "Sky Lagoon — Saman", detail: "14:00 slot · Dec 12 · ~€67/person", category: "spa", confirmationKey: "lagoon_conf", linkKey: "lagoon_link", url: "https://www.skylagoon.com", booked: false },
];

export const PACK_LIST = [
  { id: "pk1", label: "Thermal base layers (top + bottom)", category: "clothing" },
  { id: "pk2", label: "Fleece mid-layer", category: "clothing" },
  { id: "pk3", label: "Waterproof windproof outer jacket", category: "clothing" },
  { id: "pk4", label: "Waterproof trousers / ski pants", category: "clothing" },
  { id: "pk5", label: "Wool socks (x3 pairs)", category: "clothing" },
  { id: "pk6", label: "Waterproof hiking boots / shoes", category: "clothing" },
  { id: "pk7", label: "Warm hat covering ears", category: "clothing" },
  { id: "pk8", label: "Neck gaiter / balaclava", category: "clothing" },
  { id: "pk9", label: "Thermal gloves + waterproof outer gloves", category: "clothing" },
  { id: "pk10", label: "Sunglasses (snow glare)", category: "clothing" },
  { id: "pk11", label: "Camera + extra batteries (cold drains them)", category: "gear" },
  { id: "pk12", label: "Power bank (large, min 20,000 mAh)", category: "gear" },
  { id: "pk13", label: "Micro USB + USB-C cables", category: "gear" },
  { id: "pk14", label: "Universal EU adapter", category: "gear" },
  { id: "pk15", label: "Head torch + extra AAA batteries", category: "gear" },
  { id: "pk16", label: "Tripod for aurora photos", category: "gear" },
  { id: "pk17", label: "Phone waterproof case", category: "gear" },
  { id: "pk18", label: "Thermos flask (1L)", category: "gear" },
  { id: "pk19", label: "Parka app (+ EasyPark) — add plate on arrival", category: "apps" },
  { id: "pk20", label: "Checkit.is bookmarked", category: "apps" },
  { id: "pk21", label: "vedur.is aurora page bookmarked", category: "apps" },
  { id: "pk22", label: "road.is bookmarked", category: "apps" },
  { id: "pk23", label: "saeferdin.is bookmarked (Grótta tides)", category: "apps" },
  { id: "pk24", label: "Google Maps offline — download Iceland map", category: "apps" },
  { id: "pk25", label: "Travel insurance documents", category: "docs" },
  { id: "pk26", label: "Passports (valid 6+ months)", category: "docs" },
  { id: "pk27", label: "European Health Insurance Card (EHIC)", category: "docs" },
  { id: "pk28", label: "Driving licence (both drivers)", category: "docs" },
  { id: "pk29", label: "Credit card (no foreign fees)", category: "docs" },
  { id: "pk30", label: "Cash ISK (small amount — most places card only)", category: "docs" },
  { id: "pk31", label: "Lip balm + moisturiser (wind chapping)", category: "health" },
  { id: "pk32", label: "Hand warmers (disposable, pack of 10)", category: "health" },
  { id: "pk33", label: "Any prescription medication", category: "health" },
  { id: "pk34", label: "Blister plasters (lots of walking)", category: "health" },
  { id: "pk35", label: "Snacks for the car (nuts, energy bars)", category: "food" },
];

export const DAYS = [
  {
    id: 1,
    date: "Tue Dec 9",
    title: "Arrival + Lava Tunnel & Northern Lights",
    badge: "Light day • Tour night",
    badgeColor: "#EEEDFE",
    badgeText: "#3C3489",
    kmDriving: 60,
    parkingEur: 0,
    walkingKm: "Minimal — rest day",
    routeKey: 1,
    stops: [
      {
        id: "d1s1", time: "14:30", icon: "✈️", name: "Arrive KEF · Collect Toyota Yaris Cross",
        note: "4AM start from Berlin — take it easy. Drive ~45 min to Hotel 201. Register rental plate in Parka + EasyPark apps at the car counter before driving off. Ask for N1 fuel discount chip at pickup.",
        tags: ["~45 min to hotel", "Ask for N1 chip at pickup"], parking: "Hotel 201 — free on-site parking", cost: null,
        mapsUrl: "https://maps.google.com/?q=Keflavik+International+Airport", category: "transport",
      },
      {
        id: "d1s1b", time: "15:00", icon: "⛽", name: "Fill up — N1 Keflavík (on way to hotel)",
        note: "Fill the tank on your way from KEF to the hotel — don't leave it for later. Use your Lotus N1 chip on the reader before inserting your Wise card. Select ISK not EUR. 95 unleaded petrol (green nozzle). This is your baseline full tank for the whole trip.",
        tags: ["N1 station · Use Lotus chip", "95 unleaded · green nozzle", "Wise card · select ISK", "~€20–25 to fill"],
        cost: 25,
        mapsUrl: "https://maps.google.com/?q=N1+petrol+station+Keflavik+Iceland", category: "transport",
      },
      {
        id: "d1s2", time: "16:30", icon: "🍜", name: "Dinner — Loving Hut",
        note: "Fully vegan Asian restaurant. Big soups, noodles, generous portions. ~20 min from hotel. Open until 9pm. Eat well before the long evening tour.",
        tags: ["100% vegan", "€12–15/person", "4.7★ · 469 reviews"], cost: 30,
        mapsUrl: "https://maps.google.com/?q=Loving+Hut+Laugavegur+Reykjavik", category: "food",
      },
      {
        id: "d1s3", time: "18:30", icon: "🛋️", name: "Rest at hotel · Layer up",
        note: "Charge camera batteries + power banks. Thermal base layer + fleece + windproof outer. Be at pickup point 15 min early. It will be very cold in the countryside.",
        tags: ["Pickup: central Reykjavík", "Be there by 19:15"], cost: null,
        mapsUrl: null, category: "rest",
      },
      {
        id: "d1s4", time: "19:30", icon: "🌌", name: "Lava Tunnel & Northern Lights Tour",
        note: "Bus picks up 19:30 from central Reykjavík. Visit Raufarhólshellir lava cave + aurora chasing in dark countryside. Helmets, headlamps & hot drinks included. ~4–5h, back ~midnight. Free re-try if no aurora!",
        tags: ["adventures.is · Pre-booked", "Free re-try guaranteed"], cost: null,
        mapsUrl: "https://maps.google.com/?q=Raufarholshellir+Lava+Tunnel+Iceland", category: "aurora",
      },
    ],
    aurora: { name: "Tour handles aurora tonight", note: "Guide monitors forecast + drives to best location. Nothing to plan — just enjoy.", free: true },
  },
  {
    id: 2,
    date: "Wed Dec 10",
    title: "South Coast",
    badge: "Full day • 360 km",
    badgeColor: "#E6F1FB",
    badgeText: "#0C447C",
    kmDriving: 360,
    parkingEur: 21,
    walkingKm: "4–5 km total",
    routeKey: 2,
    stops: [
      {
        id: "d2s1", time: "08:30", icon: "☕", name: "Breakfast at Hotel 201 (included) · Depart 09:30",
        note: "Pack thermos + snacks from Bónus. Biggest driving day — leave by 09:30 to make the most of the 4.5h of daylight.",
        tags: ["Breakfast included", "⛽ Tank already full from Day 1"], cost: null, mapsUrl: null, category: "food",
      },
      {
        id: "d2s2", time: "11:10", icon: "💧", name: "Seljalandsfoss Waterfall",
        note: "Walk behind the waterfall curtain — magical in winter but path can close if too icy. Allow 40–45 min.",
        tags: ["Free entry", "4.8★ · 3,418 reviews", "1h 40min from hotel"],
        parking: "€7 (1,000 ISK) · Checkit.is or card kiosk", cost: 7,
        walking: "~0.8 km flat loop around waterfall",
        mapsUrl: "https://maps.google.com/?q=Seljalandsfoss+waterfall+Iceland",
        category: "nature", warning: "Icy path possible — waterproof shoes essential",
      },
      {
        id: "d2s2b", time: "12:00", icon: "🪨", name: "Nauthúsagil Gorge (Bull Shed Ravine) — hidden gem",
        note: "Just 5 min drive from Seljalandsfoss. Park at small roadside pull-off on Route 249. Walk inside the gorge — 10–15 min each way stepping over stones with chains for support. At the end: a stunning hidden waterfall completely inside the gorge. In December the stream may be partially frozen making it even more dramatic. Almost nobody visits this — you'll likely have it to yourselves. Waterproof boots essential.",
        tags: ["Free entry", "Almost no crowds", "~5 min from Seljalandsfoss"],
        parking: "Free roadside pull-off · no fee", cost: null,
        walking: "~1 km each way inside gorge · slippery stones · chains for support",
        mapsUrl: "https://maps.google.com/?q=Nauthusagil+gorge+Iceland",
        category: "nature", warning: "Stepping stones in stream — waterproof boots essential, go slow",
      },
      {
        id: "d2s3", time: "13:00", icon: "💧", name: "Skógafoss Waterfall",
        note: "20 min east. Iceland's most photogenic waterfall. Climb the staircase on the right for elevated views. Winter spray freezes beautifully. Allow 40 min.",
        tags: ["Free entry", "4.9★ · 4,379 reviews"],
        parking: "€7 (1,000 ISK) · Parka location 8205 · 8h valid", cost: 7,
        walking: "~0.5 km flat to base · optional 370 steps up staircase",
        mapsUrl: "https://maps.google.com/?q=Skogafoss+waterfall+Iceland", category: "nature",
      },
      {
        id: "d2s3b", time: "13:45", icon: "🌊", name: "Kvernufoss — secret walk-behind waterfall",
        note: "Same car park as Skógafoss — no extra parking cost! Walk behind the Skógar Museum, follow the fence to stairs, then follow the path into the valley. 15–20 min walk each way. 30m waterfall hidden in a gorge — you can walk behind it like Seljalandsfoss but with almost zero crowds. Covered in green moss, open sky above. Many say this is their favourite waterfall in Iceland.",
        tags: ["Free entry", "Same parking as Skógafoss", "Almost no crowds"],
        parking: "Included in Skógafoss parking already paid", cost: null,
        walking: "~1.5 km return · mostly flat · 15–20 min each way",
        mapsUrl: "https://maps.google.com/?q=Kvernufoss+waterfall+Iceland",
        category: "nature",
      },
      {
        id: "d2s4", time: "14:30", icon: "🍲", name: "Lunch — Suður-Vík, Vík village",
        note: "30 min drive east to Vík. Best restaurant on the South Coast. Vegetable soup + bread — warm, filling, very affordable. Open noon–9pm.",
        tags: ["Veggie soup ✓", "4.7★ · 2,856 reviews", "Open noon–9pm"], cost: 20,
        mapsUrl: "https://maps.google.com/?q=Sudur+Vik+restaurant+Vik+Iceland", category: "food",
      },
      {
        id: "d2s4b", time: "15:15", icon: "⛽", name: "⛽ Fill up — N1 Vík (critical stop)",
        note: "CRITICAL — fill up here before glacier and Dyrhólaey. No petrol stations for the next 30 km of remote road. Use Lotus N1 chip on reader first, then Wise card. Select ISK not EUR. Takes 5 min — don't skip.",
        tags: ["⚠️ Last station for 30+ km", "N1 Vík · Use Lotus chip", "Wise card · select ISK"],
        cost: 20,
        mapsUrl: "https://maps.google.com/?q=N1+petrol+station+Vik+Iceland", category: "transport",
        warning: "Do not skip — no stations between Vík and Reynisfjara",
      },
      {
        id: "d2s5", time: "15:30", icon: "🏔️", name: "Sólheimajökull Glacier",
        note: "15 min west of Vík. Short 10-min flat walk to the glacier tongue. Black volcanic ash on white ice — surreal December scenery. Allow 30–35 min.",
        tags: ["Free entry", "4.9★ · 357 reviews"],
        parking: "€7 (1,000 ISK) · Parka", cost: 7,
        walking: "~1 km flat return to glacier viewpoint",
        mapsUrl: "https://maps.google.com/?q=Solheimajokull+glacier+Iceland", category: "nature",
      },
      {
        id: "d2s6", time: "16:15", icon: "🌊", name: "Dyrhólaey Arch & Lighthouse — replaces DC-3",
        note: "20 min drive. A 120-metre natural arch of volcanic rock rising from the ocean — gateway to the sea. Drive up to the lower car park for arch views, then continue to the lighthouse at the top for a full panoramic view over the entire South Coast: Reynisfjara, Vík village, glaciers in the distance. Completely free, completely self-driven. In December no bird nesting restrictions. Views are extraordinary at dusk. Allow 40 min.",
        tags: ["Free entry", "Panoramic South Coast views", "No timeslots, no tours"],
        parking: "Free parking at lower viewpoint + lighthouse", cost: null,
        walking: "~0.5 km flat to arch viewpoint · road continues to lighthouse",
        mapsUrl: "https://maps.google.com/?q=Dyrholaey+arch+lighthouse+Iceland",
        category: "nature",
      },
      {
        id: "d2s7", time: "17:05", icon: "🏖️", name: "Reynisfjara Black Sand Beach",
        note: "10 min from Dyrhólaey. Basalt columns + Reynisdrangar sea stacks. Dark by arrival — use phone torch. Extraordinary at night. Stay for aurora if sky clears.",
        tags: ["Free entry", "4.8★ · 2,440 reviews"],
        parking: "€7 lower / €5 upper · Parka loc 8202 · 3h", cost: 7,
        walking: "~0.5 km flat beach walk",
        mapsUrl: "https://maps.google.com/?q=Reynisfjara+black+sand+beach+Iceland",
        category: "nature", warning: "⚠️ DANGER: Rogue waves fatal — stay 30m+ from waterline at all times",
      },
    ],
    aurora: { name: "Reynisfjara Beach or Vík outskirts", note: "Already there at nightfall. Zero light pollution. Stay if KP ≥ 3 + sky clear. Drive back by 20:30 (2h 30min to hotel).", free: true },
  },
  {
    id: 3,
    date: "Thu Dec 11",
    title: "Golden Circle + Faxafoss",
    badge: "Full day • 275 km",
    badgeColor: "#E6F1FB",
    badgeText: "#0C447C",
    kmDriving: 275,
    parkingEur: 28,
    walkingKm: "3–4 km total",
    routeKey: 3,
    stops: [
      {
        id: "d3s1", time: "08:30", icon: "☕", name: "Breakfast at Hotel 201 (included) · Depart 09:30",
        tags: ["Breakfast included", "⛽ Check fuel before leaving — fill if below half"], cost: null, mapsUrl: null, category: "food",
      },
      {
        id: "d3s2", time: "10:15", icon: "🌋", name: "Þingvellir National Park",
        note: "45 min drive. Walk the Almannagjá gorge between North American & Eurasian tectonic plates. Iceland's parliament site 930 AD. UNESCO World Heritage. Allow 1–1.5h.",
        tags: ["Free entry", "UNESCO", "4.7★ · 24,206 reviews"],
        parking: "€7 (1,000 ISK) · Checkit.is · Valid all lots all day", cost: 7,
        walking: "~1.5 km flat gorge walk",
        mapsUrl: "https://maps.google.com/?q=Thingvellir+National+Park+Iceland", category: "nature",
      },
      {
        id: "d3s3", time: "12:00", icon: "♨️", name: "Geysir Geothermal Area",
        note: "45 min from Þingvellir. Strokkur erupts every 5–10 min — keep camera ready! Geysir Bistro has hot vegetable soup. Allow 1h.",
        tags: ["Free entry", "4.7★ · 4,702 reviews", "Soup at Geysir Bistro"],
        parking: "€7 (1,000 ISK) · Parka", cost: 21,
        walking: "~0.5 km flat paved area around geysers",
        mapsUrl: "https://maps.google.com/?q=Geysir+geothermal+area+Iceland", category: "nature",
      },
      {
        id: "d3s4", time: "13:20", icon: "🐴", name: "Faxafoss Waterfall (Faxi)",
        note: "Just 11 km south of Geysir on Route 35 — follow signs for 'Við Faxa'. Only a 15 min drive from Geysir. Wide, calm and incredibly peaceful — 80 metres across and 7 metres tall, named after the Icelandic word for 'mane'. Far fewer crowds than Gullfoss. Features a salmon fish ladder alongside the falls. Allow 20–25 min.",
        tags: ["Free entry", "Hidden gem on Golden Circle", "Almost no crowds"],
        parking: "€6 (900 ISK) · Pay on-site", cost: 6,
        walking: "~0.3 km flat to waterfall viewpoint",
        mapsUrl: "https://maps.google.com/?q=Faxafoss+waterfall+Faxi+Iceland", category: "nature",
      },
      {
        id: "d3s5", time: "14:10", icon: "💧", name: "Gullfoss Waterfall",
        note: "9 km from Faxafoss, only 10 min drive. Two-tier cascade into a canyon. December spray freezes into stunning ice sculptures. Gullfoss café on site. Allow 45 min.",
        tags: ["Free entry", "FREE parking", "4.9★ · 5,559 reviews"],
        parking: "Free — large car park on-site", cost: null,
        walking: "~0.8 km to upper and lower viewpoints · some uneven terrain",
        mapsUrl: "https://maps.google.com/?q=Gullfoss+waterfall+Iceland", category: "nature",
      },
      {
        id: "d3s6", time: "15:15", icon: "⭕", name: "Kerið Volcanic Crater",
        note: "~55 min south. Vivid red-and-green crater with a lake inside. Walk the rim at last light or descend to the floor. Entry at gate kiosk (card). Allow 30–40 min.",
        tags: ["Entry: €4/person at kiosk", "4.5★ · 19,973 reviews"],
        parking: "Free parking · Entry fee separate", cost: 8,
        walking: "~0.8 km rim walk · optional descent to crater floor",
        mapsUrl: "https://maps.google.com/?q=Kerid+volcanic+crater+Iceland", category: "nature",
      },
      {
        id: "d3s7", time: "17:30", icon: "🍜", name: "Dinner back in Reykjavík — Loving Hut or Chickpea",
        note: "Back in Reykjavík ~17:00. Loving Hut for Asian soups or Chickpea for falafel wraps (closed Sundays). Both ~€10–15/person.",
        tags: ["Vegetarian ✓", "€10–15/person"], cost: 28,
        mapsUrl: "https://maps.google.com/?q=Chickpea+Reykjavik", category: "food",
      },
    ],
    aurora: { name: "Kleifarvatn Lake (40 min) or Heiðmörk Reserve (20 min)", note: "Head out ~19:30 after dinner. Kleifarvatn: volcanic lake, hills block city glow, water reflects lights. Heiðmörk: dark lava park, only 20 min away. Both free parking.", free: true },
  },
  {
    id: 4,
    date: "Fri Dec 12",
    title: "Reykjavík · Hallgrímskirkja · Sky Lagoon",
    badge: "Easy day • City + Spa",
    badgeColor: "#FBEAF0",
    badgeText: "#72243E",
    kmDriving: 35,
    parkingEur: 5,
    walkingKm: "3–4 km city walking",
    routeKey: 4,
    stops: [
      {
        id: "d4s1", time: "09:00", icon: "☕", name: "Breakfast at Hotel 201 (included) · Relaxed start",
        note: "Last full day. No rush. Enjoy the breakfast spread. Try Skyr from the buffet if available — Iceland's famous strained dairy, like thick yogurt, high protein and delicious. Taxi or drive to city centre.",
        tags: ["Breakfast included", "Try Skyr if available 🥛"], cost: null, mapsUrl: null, category: "food",
      },
      {
        id: "d4s2", time: "09:30", icon: "⚓", name: "Old Harbour + Tryggvagata + Sun Voyager",
        note: "Walk the Old Harbour area — Tryggvagata 19 is where Kolaportið flea market is (open Sat/Sun only, closed on your visit but the area is still great). See the iconic Sun Voyager sculpture by the waterfront. Harpa Concert Hall is right here too — striking glass architecture. Allow 30–40 min.",
        tags: ["Free entry", "Harpa Concert Hall", "Sun Voyager sculpture"],
        parking: "Harbour parking · Parka or EasyPark", cost: null,
        walking: "~1 km flat harbour walk",
        mapsUrl: "https://maps.google.com/?q=Sun+Voyager+sculpture+Reykjavik", category: "sightseeing",
      },
      {
        id: "d4s3", time: "10:00", icon: "☕", name: "☕ Reykjavík Röst — harbour café",
        note: "Right at the Old Harbour. Café and wine bar with sourdough sandwiches, homemade cakes, excellent coffee and vegan options. Quiet spot with scenic views over the marina. Perfect warm-up before the church walk. Arctic Adventures guide specifically recommends it.",
        tags: ["Vegan options ✓", "Harbour views", "Homemade cakes"],
        parking: "Harbour parking", cost: 18,
        mapsUrl: "https://maps.google.com/?q=Reykjavik+Rost+harbour+cafe", category: "cafe",
      },
      {
        id: "d4s4", time: "10:45", icon: "⛪", name: "Hallgrímskirkja Church + Tower",
        note: "Opens 9am. Take the elevator to the tower observation deck — 360° panoramic views over Reykjavík, the harbour and mountains. Church interior free. Tower entry on-site. Allow 45–60 min.",
        tags: ["Church: free", "Tower: €10/person", "4.6★ · 28,272 reviews", "Opens 9am"],
        parking: "Street parking nearby · Parka or EasyPark · ~€5/hr", cost: 25,
        walking: "~0.1 km · elevator to tower · minimal walking",
        mapsUrl: "https://maps.google.com/?q=Hallgrimskirkja+church+Reykjavik", category: "sightseeing",
      },
      {
        id: "d4s5", time: "11:45", icon: "🥐", name: "☕ Brauð & Co — legendary cinnamon bun",
        note: "Steps from the church on Frakkastígur. Iceland's most famous bakery. Cinnamon rolls are world-class — soft, fragrant, not too sweet. Also try Kleinur if available — traditional Icelandic fried pastry with cardamom, a classic Christmas treat only made in December. Mostly takeaway; eat on the rainbow street steps.",
        tags: ["4.8★ · 4,719 reviews", "€4–6/item", "Ask for Kleinur 🍩 — December only"],
        parking: "Same street parking as church", cost: 14,
        walking: "~0.1 km from church · steps away",
        mapsUrl: "https://maps.google.com/?q=Braud+and+Co+bakery+Reykjavik", category: "cafe",
      },
      {
        id: "d4s6", time: "12:00", icon: "💎", name: "Jewellery shopping — Metal Design + backup options",
        note: "Primary stop: Metal Design (Skólavörðustígur 2, bottom of Rainbow Street). Owner Stefán Bogi is an Icelandic gold & silversmith — all pieces handmade in his workshop. Sells rings, necklaces, bracelets and earrings inspired by Iceland's coast and nature. One reviewer bought a lava rock ring with a band showing Iceland's skyline (mountains, volcanoes, glaciers). ⚠️ Important: lava stones in many Reykjavík shops come from Hawaii not Iceland (lava is too soft). Also note the shop is owner-run and has unreliable hours — some visitors found it locked. ⚠️ BACKUP: Orrifinn Jewels (Skólavörðustígur 43, further up the same street) — voted Best Jewellery Store in Reykjavík multiple times, also fully handmade, very reliable. If Metal Design is closed, walk up to Orrifinn.",
        tags: ["Metal Design: Skólavörðustígur 2", "Orrifinn backup: No. 43", "⚠️ Metal Design hours unreliable", "€20–100+"],
        cost: 40,
        walking: "~0.5 km walk down Rainbow Street from church",
        warning: "Metal Design may be closed — Orrifinn Jewels at Skólavörðustígur 43 is the reliable backup on same street",
        mapsUrl: "https://maps.google.com/?q=Metal+Design+Skolavordustigur+2+Reykjavik", category: "sightseeing",
      },
      {
        id: "d4s7", time: "12:20", icon: "🌈", name: "Skólavörðustígur (Rainbow Street) + Laugavegur shopping",
        note: "Walk down the rainbow-painted street to Laugavegur — Reykjavík's main shopping strip. Browse local wool (Lopapeysa sweaters), lava jewellery, bookshops, Icelandic candy (lakkrís). Allow 1–1.5h.",
        tags: ["Walking — no driving needed", "Lopapeysa wool sweaters", "Icelandic candy"], cost: null,
        walking: "~1 km Rainbow Street + Laugavegur combined",
        mapsUrl: "https://maps.google.com/?q=Skolavordustigur+Rainbow+Street+Reykjavik", category: "sightseeing",
      },
      {
        id: "d4s8", time: "13:15", icon: "🧆", name: "Lunch — Chickpea (4.9★) or 101 Street Food",
        note: "Chickpea: outstanding falafel wraps with hummus, kimchi, pickled tomato. 4.9★ / 449 reviews. ~€11. Or 101 Street Food (steps from church): veggie soup + unlimited bread ~€8–10 — Arctic Adventures guide specifically highlights it. Chickpea closed Sundays.",
        tags: ["Vegetarian ✓", "4.9★ Chickpea", "€8–13/person", "Chickpea closed Sundays"], cost: 24,
        mapsUrl: "https://maps.google.com/?q=Chickpea+restaurant+Reykjavik", category: "food",
      },
      {
        id: "d4s9", time: "14:00", icon: "☕", name: "☕ Sandholt Bakery — coffee & cream puffs",
        note: "Laugavegur 36 — right on the shopping street. Family-run since the 1920s. Famous cream puffs, Danish pastries, organic sourdough, excellent oat latte. Sit-down seating available. Go early to avoid queues.",
        tags: ["4.6★ · 4,285 reviews", "€5–8/item", "Open 7:30am–6pm"],
        parking: "Street parking · Parka", cost: 20,
        mapsUrl: "https://maps.google.com/?q=Sandholt+bakery+Laugavegur+Reykjavik", category: "cafe",
      },
      {
        id: "d4s10", time: "14:45", icon: "🌊", name: "Sky Lagoon — sunset & blue hour",
        note: "5 min from Hotel 201. Arrive ~14:45 to catch sunset (~15:30) from the infinity edge over the Atlantic. Saman package: lagoon → cold pool → sauna → cold mist → sky bath → steam → salt scrub + shower. ⚠️ IMPORTANT: shower thoroughly WITHOUT your swimsuit before entering — strictly enforced. Open until 11pm — no need to rush.",
        tags: ["Pre-book: skylagoon.com", "Saman ~€67/person", "4.7★ · 9,018 reviews", "⚠️ Shower without swimsuit first"],
        parking: "Free on-site · No time limit", cost: 134,
        mapsUrl: "https://maps.google.com/?q=Sky+Lagoon+Reykjavik", category: "spa",
      },
      {
        id: "d4s11", time: "17:30", icon: "🍜", name: "Farewell dinner — Loving Hut",
        note: "Hearty Asian soups and noodles. Big portions, very affordable. Open until 9pm (Sunday from 4pm). Early dinner to give time for the aurora spot.",
        tags: ["Vegan ✓", "€12–15/person"], cost: 30,
        mapsUrl: "https://maps.google.com/?q=Loving+Hut+Laugavegur+Reykjavik", category: "food",
      },
      {
        id: "d4s12", time: "19:00", icon: "🍩", name: "☕ Loo.koo.mas — Greek donuts & hot chocolate",
        note: "On the way from dinner to Grótta. The highest-rated sweet spot in Reykjavík (4.9★). Greek loukoumades (honey-drenched donuts) + rich hot chocolate. Perfect warm fuel before aurora hunting in the cold. Open until 11pm.",
        tags: ["4.9★ · 1,560 reviews", "€6–9/portion", "Open 2:30pm–11pm"], cost: 16,
        mapsUrl: "https://maps.google.com/?q=Lookumas+Laugavegur+Reykjavik", category: "cafe",
      },
    ],
    aurora: { name: "Grótta Lighthouse — just 15 min from hotel", note: "Reviewers call it 'the best place to see Northern Lights in Reykjavík'. Open ocean north = unobstructed horizon. Geothermal foot bath on-site to keep warm. Check tide at saeferdin.is before walking — path floods at high tide. Free roadside parking.", free: true },
  },
  {
    id: 5,
    date: "Sat Dec 13",
    title: "Departure Day",
    badge: "Morning only ✈️",
    badgeColor: "#FAEEDA",
    badgeText: "#633806",
    kmDriving: 50,
    parkingEur: 0,
    walkingKm: "Minimal — airport only",
    routeKey: 5,
    stops: [
      {
        id: "d5s1", time: "06:30", icon: "☕", name: "Early breakfast + checkout",
        note: "Ask hotel the evening before what time breakfast opens for early departures. Pack bags the night before. Leave hotel no later than 07:15 for a 10:00–12:00 departure flight.",
        tags: ["Breakfast included", "⚠️ Leave hotel by 07:15"], cost: null, mapsUrl: null,
        category: "food", warning: "Leave hotel no later than 07:15",
      },
      {
        id: "d5s2", time: "07:15", icon: "🚗", name: "Drive toward KEF",
        note: "~45 min drive from hotel. Head toward Keflavík — fill up at the N1 or Olis station BEFORE reaching the Lotus drop-off. Return car to Lotus office at Flugvellir 6, 230 Keflavík. Allow 30 min for car return + free shuttle to terminal.",
        tags: ["Fill tank BEFORE car return", "Lotus office: Flugvellir 6 Keflavík"],
        parking: "KEF return bay — free drop-off", cost: null,
        mapsUrl: "https://maps.google.com/?q=Lotus+Car+Rental+Flugvellir+6+Keflavik",
        category: "transport",
      },
      {
        id: "d5s2b", time: "07:30", icon: "⛽", name: "⛽ Fill up — Olis or N1 Keflavík town (BEFORE car return)",
        note: "MUST DO before returning the car to Lotus. Return policy is full-to-full — if you return without a full tank, Lotus fills it at premium rates and charges your card. Olis station is in Keflavík town, just before the Lotus office. Use N1 chip if you find an N1 instead. Wise card + select ISK.",
        tags: ["⚠️ Full-to-full policy", "Olis or N1 in Keflavík town", "N1 chip if available", "Wise card · select ISK"],
        cost: 15,
        mapsUrl: "https://maps.google.com/?q=Olis+petrol+station+Keflavik+Iceland",
        category: "transport",
        warning: "Return car with FULL tank — charged at premium if not filled",
      },
      {
        id: "d5s3", time: "09:00", icon: "✈️", name: "Check in · KEF → AMS → BER",
        note: "HV 6888 → KL 1785. Enjoy a great Iceland trip memory on the flight home!",
        tags: ["HV 6888 → KL 1785"], cost: null,
        mapsUrl: null, category: "transport",
      },
    ],
    aurora: null,
  },
];

export const COST_BREAKDOWN = [
  { label: "Toyota Yaris Cross 4x4 Hybrid rental", eur: 287, note: "Full zero-excess coverage · Free 4G WiFi · Dec 9–13", category: "transport" },
  { label: "Lava Tunnel + Aurora Tour (x2)", eur: 380, note: "Pre-booked · adventures.is", category: "experience" },
  { label: "Sky Lagoon Saman (x2)", eur: 134, note: "Pre-book at skylagoon.com", category: "experience" },
  { label: "Hallgrímskirkja Tower (x2)", eur: 20, note: "€10/person, on-site", category: "sightseeing" },
  { label: "Kerið Crater entry (x2)", eur: 8, note: "€4/person at kiosk", category: "sightseeing" },
  { label: "DC-3 Shuttle (x2 return)", eur: 56, note: "€14/way × 2 people, or walk free", category: "transport" },
  { label: "Parking (4 days incl. Faxafoss)", eur: 58, note: "Parka + EasyPark + Checkit.is + Faxafoss on-site", category: "transport" },
  { label: "Fuel — hybrid (whole trip est.)", eur: 80, note: "Yaris Cross ~20km/litre · Fill at Vík Day 2 + Olis KEF Day 5", category: "transport" },
  { label: "Dinners (est. 4 evenings)", eur: 116, note: "Loving Hut, Chickpea, 101 Street Food", category: "food" },
  { label: "Lunches on road (3 days)", eur: 55, note: "Suður-Vík, Geysir Bistro, café soups", category: "food" },
  { label: "Cafes + pastries (Day 4 city walk)", eur: 68, note: "Reykjavík Röst + Brauð & Co + Sandholt + Loo.koo.mas + Kleinur", category: "food" },
  { label: "Metal Design — lava jewellery", eur: 30, note: "Handmade Icelandic lava · Rainbow Street", category: "shopping" },
  { label: "Supermarket snacks (Bónus)", eur: 30, note: "Stock up for road days · ISK cash useful", category: "food" },
];
